#!/usr/bin/env python3
"""Reproducible diagnostic geometry, NOT finished Paco/gatita artwork. No dependencies."""
from pathlib import Path
import struct, zlib, re, json
ROOT = Path(__file__).resolve().parents[1]
DIGITS = ['111101101101111','010110010010111','111001111100111','111001111001111','101101111001001','111100111001111','111100111101111','111001001001001','111101111101111','111101111001111']
def png(path,w,h,data):
    def chunk(t,d): return struct.pack('>I',len(d))+t+d+struct.pack('>I',zlib.crc32(t+d))
    raw=b''.join(b'\0'+data[y*w*4:(y+1)*w*4] for y in range(h))
    path.write_bytes(b'\x89PNG\r\n\x1a\n'+chunk(b'IHDR',struct.pack('>IIBBBBB',w,h,8,6,0,0,0))+chunk(b'tEXt',b'Source\0Original diagnostic geometry generated by scripts/generate-fixtures.py; not character artwork.')+chunk(b'IDAT',zlib.compress(raw))+chunk(b'IEND',b''))
def atlas(folder, color):
    w,h=1024,512; data=bytearray(w*h*4)
    def rect(x,y,rw,rh,c):
        for yy in range(max(0,y),min(h,y+rh)):
            for xx in range(max(0,x),min(w,x+rw)): data[(yy*w+xx)*4:(yy*w+xx)*4+4]=bytes(c)
    for n in range(32):
        x,y=(n%8)*128,(n//8)*128; pose=n//8; bob=n%3
        rect(x+30,y+42+bob*2,64,68-bob*2,color)
        # Asymmetric right-facing arrow, feet, top-left marker and frame number.
        for j in range(14): rect(x+94,y+61+j,14-abs(7-j),1,(250,250,240,255))
        rect(x+34+(n%2)*6,y+110,18,6,(30,32,38,255)); rect(x+72-(n%2)*6,y+110,18,6,(30,32,38,255))
        rect(x+43,y+58,8,8,(25,30,35,255)); rect(x+70,y+58,8,8,(25,30,35,255))
        rect(x+42,y+84,36,4+pose*3,(250,250,240,255))
        rect(x+8,y+8,8,8,(235,70,50,255)); rect(x+60,y+114,8,3,(250,70,140,255))
        for k,ch in enumerate(f'{n:02}'):
            for i,v in enumerate(DIGITS[int(ch)]):
                if v=='1': rect(x+51+k*16+(i%3)*4,y+20+(i//3)*4,4,4,(250,250,240,255))
    png(folder/'atlas.png',w,h,data)
    preview=b''.join(data[y*w*4:y*w*4+128*4] for y in range(128)); png(folder/'preview.png',128,128,preview)
base='''schema = 1
id = "{id}"
name = "{name}"
author = "NotAVirus — diagnostic fixture, not final art"
version = 1
tile = [128, 128]
anchor = [64, 116]
filter = "{filter}"
[atlas]
file = "atlas.png"
grid = [8, 4]
'''
paco=re.search(r'```toml\n(schema = 1\nid = "paco".*?)```', (ROOT/'specs/not-a-virus-spec.md').read_text(),re.S).group(1)
gatita='''
[behavior]
preset = "chase"
idle = "play_roll_purr"
moving = "bound"
start_moving = "crouch"
stop_moving = "settle"
sleep = "curl_up_asleep"
wake = "stretch"
idle_delay_ms = 180
sleep_after_ms = 18000
[motion]
max_speed = 420
acceleration = 1600
stop_distance = 18
start_distance = 32
[states.play_roll_purr]
frames = [0, 1, 2, 3, 4, 5, 4, 0]
durations_ms = [180, 120, 120, 200, 160, 300, 200, 220]
loop = true
[states.bound]
frames = [8, 9, 10, 11]
fps = 14
[states.crouch]
frames = [16, 17]
fps = 12
loop = false
[states.settle]
frames = [18, 19]
durations_ms = [80, 160]
loop = false
interrupt = "finish"
next = "tail_flick"
[states.tail_flick]
frames = [20, 21]
fps = 10
loop = false
interrupt = "on_move"
[states.curl_up_asleep]
frames = [24, 25]
fps = 2
[states.stretch]
frames = [26, 27, 28]
fps = 10
loop = false
'''
default='''
[behavior]
turn = "turn"
sleep = "sleep"
[states.idle]
frames = [0, 1]
fps = 3
[states.run]
frames = [8, 9, 10, 11]
fps = 12
[states.turn]
frames = [20, 21]
fps = 10
loop = false
[states.sleep]
frames = [24, 25]
fps = 2
'''
for id,name,color,extra in [('default','Default',(39,163,122,255),default),('paco','Paco',(42,126,218,255),None),('gatita','gatita',(192,133,73,255),gatita)]:
    folder=ROOT/'tests/fixtures/diagnostic'/id; folder.mkdir(parents=True,exist_ok=True)
    (folder/'pack.toml').write_text(paco if id=='paco' else base.format(id=id,name=name,filter='linear' if id=='gatita' else 'nearest')+extra)
    atlas(folder,color)
# Minimal and named-region fixtures exercise both atlas encodings.
for id in ['minimal','regions']:
    folder=ROOT/'tests/fixtures'/id; folder.mkdir(parents=True,exist_ok=True); atlas(folder,(130,80,190,255))
    source=base.format(id=id,name=id,filter='nearest')+'\n[states.idle]\nframes = [0, 1]\n[states.run]\nframes = [8, 9]\n'
    if id=='regions':
        source=source.replace('grid = [8, 4]','regions = "atlas.json"').replace('[0, 1]','["top", "right"]').replace('[8, 9]','["bottom", "middle"]')
        (folder/'atlas.json').write_text(json.dumps({name:dict(x=x,y=y,w=128,h=128) for name,x,y in [('top',0,0),('right',128,0),('bottom',0,384),('middle',128,128)]},indent=2))
    (folder/'pack.toml').write_text(source)
