const base = process.env.ASSEMBLAVATAR_URL || "http://127.0.0.1:3000";
const benchmark = await Bun.file("data/benchmarks/house.json").json();
async function call(path: string, data?: unknown) { const response = await fetch(`${base}/api${path}`, data ? { method: "POST", headers: data instanceof FormData ? {} : {"Content-Type":"application/json"}, body:data instanceof FormData ? data : JSON.stringify(data) } : undefined); const body = await response.json() as any; if (!response.ok) throw Error(body.error?.message); return body; }
const a = await call(`/assemblages/${benchmark.assemblageId}`);
const response = await fetch(`${base}/api/assets/${a.revision.previewAssetIds[0]}`);
const form = new FormData(); form.set("file",new File([await response.arrayBuffer()],"synthetic-house-reference.png",{type:"image/png"})); form.set("role","front"); form.set("description","Synthetic test reference rendered from the first generated revision. This is not a photograph.");
await call(`/assemblages/${a.id}/references`,form);
const result = await call(`/assemblages/${a.id}/refine`,{instruction:"Make the flat roof terracotta red. Keep all house geometry, windows and the recessed entrance unchanged. The reference is the prior revision; the new roof colour should override it.",profile:"architectural-object",maxIterations:1,automaticRefinement:false});
let previous = ""; const start = Date.now();
while (true) { const job = await call(`/jobs/${result.jobId}`); if (job.phase!==previous) {console.info(job.phase);previous=job.phase;} if (!["queued","running"].includes(job.status)) { if (["failed","cancelled"].includes(job.status)) throw Error(job.error); const current = await call(`/assemblages/${a.id}`); if (current.source.code===a.source.code) throw Error("Refinement did not change the source"); const report = {assemblageId:a.id,status:job.status,revision:current.currentRevision,referenceType:"synthetic rendered reference",evaluation:current.revision.evaluation,durationMs:Date.now()-start}; await Bun.write("data/benchmarks/house-refinement.json",JSON.stringify(report,null,2));console.info(JSON.stringify(report,null,2));break;} if (Date.now()-start>300000) {await call(`/jobs/${result.jobId}/cancel`,{});throw Error("Refinement test timed out");} await Bun.sleep(1000); }
