import { test, expect, type Page } from '@playwright/test';
async function newSession(page: Page) {
  await page.goto('/'); await expect(page.getByText('Codex connected', { exact: true })).toBeVisible();
  if (await page.getByText('Your projects will appear here.').isVisible()) {
    await page.getByRole('button', { name: 'Add workspace', exact: true }).click();
    await page.getByLabel('Name', { exact: true }).fill('Canvas test workspace');
    await page.getByLabel('Absolute folder path').fill(process.env.CANVAS_E2E_DIR!);
    await page.getByRole('dialog').getByRole('button', { name: 'Add workspace', exact: true }).click();
    await expect(page.getByRole('dialog')).not.toBeVisible();
  }
  await page.getByRole('button', { name: '＋ New session' }).click(); await expect(page.getByRole('textbox', { name: 'Message Codex' })).toBeVisible();
}
test('streaming, artifacts, drag/resize, collapse and reload restore the same session', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await newSession(page);
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('Fix the animation export'); await page.getByRole('button', { name: 'Send ↑' }).click();
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  await page.locator('.card-activity summary').filter({ hasText: 'bun test export' }).click();
  await expect(page.locator('.terminal-output')).toContainText(/Running export tests|47 tests passed/);
  await expect(page.locator('.message-text').filter({ hasText: 'All 47 tests pass.' })).toBeVisible();
  await expect(page.locator('.card')).toHaveCount(4);
  expect(await page.evaluate(() => (window as any).injected)).toBeUndefined();
  await expect(page.locator('.messages table')).toBeVisible();
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  const diff = page.locator('.card-diff'), header = diff.locator('.card-header');
  const before = await diff.evaluate(e => ({ x: e.style.left, y: e.style.top, width: e.style.width }));
  const box = await header.boundingBox(); if (!box) throw new Error('Missing diff header');
  await page.mouse.move(box.x + 55, box.y + 20); await page.mouse.down(); await page.mouse.move(box.x - 70, box.y - 50, { steps: 10 }); await page.mouse.up();
  await expect.poll(() => diff.evaluate(e => e.style.left)).not.toBe(before.x);
  const resize = await diff.locator('.resize-handle').boundingBox(); if (!resize) throw new Error('Missing resize handle');
  await page.mouse.move(resize.x + resize.width / 2, resize.y + resize.height / 2); await page.mouse.down(); await page.mouse.move(resize.x + 80, resize.y + 70, { steps: 8 }); await page.mouse.up();
  await expect.poll(() => diff.evaluate(e => e.style.width)).not.toBe(before.width);
  const saved = await diff.evaluate(e => ({ x: e.style.left, y: e.style.top, width: e.style.width, height: e.style.height }));
  await diff.getByRole('button', { name: 'Collapse or expand card' }).click(); await expect(diff).toHaveClass(/collapsed/);
  const zoom = await page.locator('#zoom-level').textContent();
  const thread = await page.evaluate(() => localStorage.getItem('canvas.thread'));
  await page.waitForTimeout(300); await page.reload();
  await expect(page.locator('.card-diff')).toHaveClass(/collapsed/);
  expect(await page.evaluate(() => localStorage.getItem('canvas.thread'))).toBe(thread);
  expect(await diff.evaluate(e => ({ x: e.style.left, y: e.style.top, width: e.style.width }))).toEqual({ x: saved.x, y: saved.y, width: saved.width });
  await expect(page.locator('#zoom-level')).toHaveText(zoom!);
  await expect(page.locator('.user-message')).toHaveCount(1);
  await page.getByRole('button', { name: 'Conversation', exact: false }).last().click();
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('Now simplify the implementation'); await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.locator('.user-message')).toHaveCount(2);
  expect(errors).toEqual([]);
  await page.screenshot({ path: 'test-results/canvas-session.png' });
});
test('mid-turn steering, reload while running, and Stop use the active Codex turn', async ({ page }) => {
  await newSession(page); const input = page.getByRole('textbox', { name: 'Message Codex' });
  await input.fill('slow inspection'); await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.getByRole('button', { name: 'Add to current turn ↑' })).toBeEnabled();
  await input.fill('Keep the public API unchanged'); await page.getByRole('button', { name: 'Add to current turn ↑' }).click();
  await expect(page.locator('.user-message')).toHaveCount(2); await page.reload();
  await expect(page.getByRole('button', { name: '■ Stop' })).toBeVisible(); await page.getByRole('button', { name: '■ Stop' }).click();
  await expect(page.locator('.turn-state')).toHaveText('interrupted'); await expect(page.getByRole('button', { name: 'Send ↑' })).toBeEnabled();
  await expect(page.locator('.card-activity .activity-state')).toHaveText('Turn interrupted · outcome unconfirmed');
});
test('network approvals survive browser reload and disappear after response', async ({ page }) => {
  await newSession(page); await page.getByRole('textbox', { name: 'Message Codex' }).fill('Fix export with approval'); await page.getByRole('button', { name: 'Send ↑' }).click();
  const approval = page.getByRole('dialog', { name: 'Codex approval request' }); await reviewRequest(page); await expect(approval).toContainText('registry.npmjs.org');
  await approval.getByRole('button', { name: 'Review later' }).click(); await expect(approval).not.toBeVisible();
  await expect(page.locator('#attention-button')).toContainText('Review approval');
  await page.reload(); await reviewRequest(page); await expect(approval).toContainText('Network access requested');
  await approval.getByRole('button', { name: 'Allow', exact: true }).click(); await expect(approval).not.toBeVisible();
  await expect(page.locator('.turn-state')).toHaveText('completed');
});
test('Codex process restart hydrates history and geometry, plus search and file previews', async ({ page }) => {
  await newSession(page);
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('Fix export before restart'); await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.locator('.turn-state')).toHaveText('completed');
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  await page.locator('.card-diff').getByRole('button', { name: 'Files' }).click();
  await page.locator('.card-diff').getByRole('button', { name: /export.ts/ }).click();
  await page.locator('.card-diff').getByRole('button', { name: 'Open file on canvas' }).click();
  await expect(page.locator('.card-file')).toContainText('const timestamp');
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  await page.locator('.card-file').getByRole('button', { name: 'Unkeep from canvas' }).click();
  await expect(page.locator('.card-file')).not.toBeVisible();
  await page.locator('.card-diff').getByRole('button', { name: 'Open file on canvas' }).click();
  await expect(page.locator('.card-file')).toBeVisible();
  await page.getByRole('button', { name: 'Search canvas' }).click();
  await page.getByRole('searchbox', { name: 'Search canvas content' }).fill('timestamp');
  await expect(page.locator('.search-result').first()).toBeVisible(); await page.locator('.search-result').first().click();
  await page.locator('.card-diff').getByRole('button', { name: 'Hide from canvas' }).click();
  await expect(page.locator('.card-diff')).not.toBeVisible();
  await page.getByRole('button', { name: 'Restore hidden artifacts' }).click();
  await expect(page.locator('.card-diff')).toBeVisible();
  await page.getByRole('button', { name: 'Conversation', exact: false }).last().click();
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('/exit-fixture'); await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.getByText('Codex offline', { exact: true })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Message Codex' })).toBeDisabled();
  await page.getByRole('button', { name: 'Restart Codex' }).click();
  await expect(page.getByText('Codex connected', { exact: true })).toBeVisible();
  await expect(page.locator('.messages')).toContainText('All 47 tests pass.');
  await expect(page.locator('.card-diff')).toBeAttached();
  await expect(page.locator('.card-file')).toContainText('const timestamp');
  await expect(page.getByRole('textbox', { name: 'Message Codex' })).toBeEnabled();
});

test('maximized reading has adjustable text, preserves layout and works for collapsed artifacts', async ({ page }) => {
  await newSession(page);
  const conversation = page.locator('.card-conversation');
  const geometry = await conversation.getAttribute('style');
  const zoom = await page.locator('#zoom-level').textContent();
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('An unsent draft');
  await conversation.getByRole('button', { name: 'Maximize card', exact: true }).click();
  const reader = page.getByRole('dialog', { name: 'Maximized card', exact: true });
  await expect(reader).toBeVisible();
  const bounds = await reader.boundingBox();
  expect(bounds!.width).toBeGreaterThan(1480); expect(bounds!.height).toBeGreaterThan(950);
  await expect(reader.getByRole('textbox', { name: 'Message Codex' })).toHaveValue('An unsent draft');
  await expect(reader.getByRole('textbox', { name: 'Message Codex' })).toHaveCSS('font-size', '20px');
  await reader.getByRole('button', { name: 'Increase reading text size' }).click();
  await reader.getByRole('button', { name: 'Increase reading text size' }).click();
  await expect(reader.getByRole('textbox', { name: 'Message Codex' })).toHaveCSS('font-size', '24px');
  await reader.locator('.card-header').hover(); await page.mouse.wheel(0, 300);
  await expect(page.locator('#zoom-level')).toHaveText(zoom!);
  await page.keyboard.press('Escape'); await expect(reader).not.toBeVisible();
  await expect(conversation).toHaveAttribute('style', geometry!);
  await expect(conversation.getByRole('button', { name: 'Maximize card', exact: true })).toBeFocused();
  await expect(page.getByRole('textbox', { name: 'Message Codex' })).toHaveValue('An unsent draft');
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('Fix export for reading');
  await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.locator('.turn-state')).toHaveText('completed');
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  const diff = page.locator('.card-diff');
  await diff.getByRole('button', { name: 'Collapse or expand card' }).click();
  const diffGeometry = await diff.getAttribute('style');
  await diff.getByRole('button', { name: 'Maximize card', exact: true }).click();
  await expect(reader.locator('.diff-line.add')).toBeVisible();
  await expect(reader.locator('.diff-line.add')).toHaveCSS('font-size', '24px');
  await page.screenshot({ path: 'test-results/maximized-diff.png' });
  await reader.getByRole('button', { name: 'Back to canvas' }).click();
  await expect(diff).toHaveClass(/collapsed/); await expect(diff).toHaveAttribute('style', diffGeometry!);
  await page.reload();
  await expect(page.locator('.card-conversation')).toBeVisible();
  await page.getByRole('button', { name: 'Maximize selected card', exact: true }).click();
  await expect(reader.getByRole('textbox', { name: 'Message Codex' })).toHaveCSS('font-size', '24px');
  await page.setViewportSize({ width: 600, height: 720 });
  await expect(reader.getByRole('button', { name: 'Back to canvas' })).toBeInViewport();
  await expect(reader.getByRole('button', { name: 'Increase reading text size' })).toBeInViewport();
  await expect(reader.getByRole('button', { name: 'Send ↑' })).toBeInViewport();
  await page.keyboard.press('Escape');
});

test('conversation, approval and artifact streaming stay live while maximized', async ({ page }) => {
  await newSession(page);
  const conversation = page.locator('.card-conversation');
  await conversation.focus(); await page.keyboard.press('m');
  const reader = page.getByRole('dialog', { name: 'Maximized card', exact: true });
  await expect(reader).toBeVisible();
  await reader.getByRole('textbox', { name: 'Message Codex' }).fill('Fix export with approval');
  await reader.getByRole('button', { name: 'Send ↑' }).click();
  const approval = page.getByRole('dialog', { name: 'Codex approval request' });
  await expect(approval).not.toBeVisible();
  await reviewRequest(page);
  await expect(approval).toContainText('registry.npmjs.org');
  await approval.getByRole('button', { name: 'Allow', exact: true }).click();
  await expect(approval).not.toBeVisible();
  await expect(reader.locator('.messages')).toContainText('All 47 tests pass.');
  await reader.locator('.artifact-reference button').filter({ hasText: 'Activity' }).first().click();
  await expect(reader.locator('.terminal-output')).toContainText('47 tests passed');
  await expect(reader.locator('.terminal-output')).toHaveCSS('font-size', '20px');
  await reader.locator('.turn-link').click();
  await expect(reader.getByRole('textbox', { name: 'Message Codex' })).toBeVisible();
  await page.screenshot({ path: 'test-results/maximized-conversation.png' });
  await reader.getByRole('button', { name: 'Back to canvas' }).click();
  await expect(page.locator('#world .card')).toHaveCount(4);
});

async function reviewRequest(page: Page) {
  await page.locator('#attention-button:visible, #reader-attention:visible').last().click();
  await page.getByRole('button', { name: /Review request/ }).click();
}
test('busy turns stay grouped, kept results survive turn changes, history selection survives reload', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await newSession(page);
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('busy inspection');
  await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.locator('.turn-state')).toHaveText('completed');
  await expect(page.locator('.card:visible')).toHaveCount(4);
  await expect(page.locator('.activity-entry')).toHaveCount(83);
  await expect(page.locator('.artifact-reference')).toHaveCount(3);
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  const first = await page.getByLabel('Visible turn').inputValue();
  const original = await page.locator('.card-activity').evaluate(e => ({ x:e.style.left,y:e.style.top }));
  const entry = page.locator('.activity-entry').filter({ hasText: 'inspect busy-0' });
  await entry.locator('summary').click(); await entry.getByRole('button', { name:'Keep on canvas', exact:true }).click();
  await expect(page.locator('.card-command')).toBeVisible();
  await page.getByRole('button', { name: 'Conversation', exact: false }).last().click();
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('slow follow-up');
  await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.locator('.turn-state').last()).toHaveText('Codex is working…');
  const latest = await page.getByLabel('Visible turn').inputValue(); expect(latest).not.toBe(first);
  await expect(page.locator('.card-command')).toBeVisible();
  expect(await page.locator('.card-activity:visible').evaluate(e => ({ x:e.style.left,y:e.style.top }))).toEqual(original);
  await page.getByLabel('Visible turn').selectOption(first);
  await expect(page.locator('.card:visible')).toHaveCount(5);
  await page.reload(); await expect(page.getByLabel('Visible turn')).toHaveValue(first);
  await page.getByRole('button', { name: '■ Stop' }).click();
  await expect(page.locator('.turn-state').last()).toHaveText('interrupted');
  await expect(page.getByLabel('Visible turn')).toHaveValue(first);
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  await page.locator('.card-command').getByRole('button', { name:'Unkeep from canvas' }).click();
  await expect(page.locator('.card:visible')).toHaveCount(4);
  await expect(page.locator('.card-activity:visible .activity-entry')).toHaveCount(83);
  await page.getByRole('button', { name: /Go to latest/ }).click();
  await expect(page.getByLabel('Visible turn')).toHaveValue(latest);
  expect(errors).toEqual([]);
});
test('failures signal attention without interrupting maximized reading', async ({ page }) => {
  await newSession(page);
  await page.locator('.card-conversation').getByRole('button', { name:'Maximize card', exact:true }).click();
  const reader = page.getByRole('dialog', { name:'Maximized card', exact:true });
  await reader.getByRole('textbox', { name:'Message Codex' }).fill('failure inspection');
  await reader.getByRole('button', { name:'Send ↑' }).click();
  await expect(reader.locator('.turn-state')).toHaveText('completed');
  await expect(page.getByRole('dialog', { name:'Needs attention', exact:true })).not.toBeVisible();
  await expect(reader.getByRole('textbox', { name:'Message Codex' })).toBeVisible();
  await reader.getByRole('button', { name:/Review approval|Past failures/ }).click();
  await page.getByRole('button', { name:/Failed.*bun test export/ }).click();
  await expect(reader.locator('.activity-entry[open]')).toContainText('Tests failed');
  await expect(reader.locator('.activity-state').first()).toHaveCSS('font-size','20px');
});

test('a new turn in another tab does not replace a maximized artifact or move the camera', async ({ page, context }) => {
  await newSession(page);
  await page.getByRole('textbox', { name: 'Message Codex' }).fill('Inspect for reading');
  await page.getByRole('button', { name: 'Send ↑' }).click();
  await expect(page.locator('.turn-state')).toHaveText('completed');
  const originalTurn = await page.getByLabel('Visible turn').inputValue();
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  await page.locator('.card-activity').getByRole('button', { name: 'Maximize card', exact: true }).click();
  const reader = page.getByRole('dialog', { name: 'Maximized card', exact: true });
  await reader.locator('summary').filter({ hasText: 'bun test export' }).click();
  const camera = await page.locator('#world').getAttribute('style');
  const other = await context.newPage(); await other.goto('/');
  await expect(other.getByRole('textbox', { name: 'Message Codex' })).toBeVisible();
  await other.getByRole('textbox', { name: 'Message Codex' }).fill('Second turn from another tab');
  await other.getByRole('button', { name: 'Send ↑' }).click();
  await expect(other.locator('.turn-state').last()).toHaveText('completed');
  await expect(reader.locator('.terminal-output')).toContainText('47 tests passed');
  await expect(reader.locator('.turn-link')).toHaveText('Turn 1');
  await expect(page.getByLabel('Visible turn')).toHaveValue(originalTurn);
  await expect(page.locator('#world')).toHaveAttribute('style', camera!);
  await page.screenshot({ path: 'test-results/maximized-activity.png' });
  await reader.getByRole('button', { name: 'Back to canvas' }).click();
  await page.getByRole('button', { name: /Go to latest/ }).click();
  await expect(page.getByLabel('Visible turn')).not.toHaveValue(originalTurn);
  await page.getByRole('button', { name: 'Fit', exact: false }).first().click();
  await page.screenshot({ path: 'test-results/grouped-canvas.png' });
  await other.close();
});
