import {describe,test,expect} from 'bun:test';
import {newProject,id,addRevision,undo,redo,addFrame,deleteFrame,moveFrame,changeFrameRevision,invalidateDescendants,assetReferences,migrateProject,serialize,selectRevision,type Asset,type Annotation} from '../src/project';
import {Camera,clamp,bounds,hit,motion} from '../src/geometry';
import {GenerationQueue,compose} from '../src/generation';
import {validateImageRequest,validatePlan} from '../server/validation';
const asset=():Asset=>({id:id(),mimeType:'image/png',width:1024,height:1024,createdAt:Date.now(),type:'GENERATED_IMAGE'});
const ann:Annotation={id:'a',kind:'arrow',points:[{x:.2,y:.3},{x:.7,y:.6}],radius:.01,color:'#fff'};
describe('revision and frame model',()=>{
 test('edit retains original and branch history, redo remembers selected child',()=>{const p=newProject(),a=addRevision(p,asset(),'original'),b=addRevision(p,asset(),'cup',a.id),c=addRevision(p,asset(),'red',b.id);expect(undo(p)).toBe(true);const d=addRevision(p,asset(),'blue',b.id);expect(p.revisions).toHaveLength(4);expect(c.parentId).toBe(d.parentId);undo(p);redo(p);expect(p.activeRevisionId).toBe(d.id);selectRevision(p,c.id);undo(p);redo(p);expect(p.activeRevisionId).toBe(c.id);});
 test('insertion, deletion and reorder keep frame identity',()=>{const p=newProject();addRevision(p,asset(),'original');const a=addFrame(p),b=addFrame(p),c=addFrame(p,p.activeRevisionId,1);expect(p.frames.map(f=>f.id)).toEqual([a.id,c.id,b.id]);moveFrame(p,b.id,0);expect(p.frames[0]!.id).toBe(b.id);deleteFrame(p,c.id);expect(p.frames).toHaveLength(2);expect(p.activeFrameId).toBe(a.id);});
 test('repair marks only dependent descendants stale and preserves old revisions',()=>{const p=newProject();const original=addRevision(p,asset(),'original'),a=addFrame(p),b=addFrame(p),c=addFrame(p),independent=addFrame(p);b.generatedFromFrameId=a.id;c.generatedFromFrameId=b.id;const replacement=addRevision(p,asset(),'repair',original.id);changeFrameRevision(p,a.id,replacement.id);expect(b.status).toBe('STALE');expect(c.status).toBe('STALE');expect(independent.status).toBe('READY');expect(p.revisions).toHaveLength(2);});
 test('stale traversal terminates even with cyclic frame dependencies',()=>{const p=newProject();addRevision(p,asset(),'original');const a=addFrame(p),b=addFrame(p);a.generatedFromFrameId=b.id;b.generatedFromFrameId=a.id;expect(invalidateDescendants(p,a.id)).toEqual([b.id]);});
 test('serialization, legacy migration and reference counting',()=>{const p=newProject(),a=asset();addRevision(p,a,'first');addRevision(p,a,'second');p.references.push(a.id);expect(assetReferences(p)[a.id]).toBe(3);const result=migrateProject(JSON.parse(serialize(p)));expect(result).toEqual(p);const legacy=JSON.parse(serialize(p));delete legacy.schemaVersion;expect(migrateProject(legacy).schemaVersion).toBe(1);});
 test('rejects broken assets, cyclic revisions and future versions',()=>{const p=newProject(),r=addRevision(p,asset(),'first');expect(()=>migrateProject({...p,schemaVersion:2})).toThrow();r.parentId=r.id;expect(()=>migrateProject(p)).toThrow();delete r.parentId;p.assets={};expect(()=>migrateProject(p)).toThrow();});
 test('in-flight frames recover as failed after reload',()=>{const p=newProject();addRevision(p,asset(),'first');addFrame(p).status='GENERATING';expect(migrateProject(JSON.parse(serialize(p))).frames[0]!.status).toBe('FAILED');});
});
describe('canvas geometry',()=>{
 test('project coordinates survive fit, pan, resize and cursor zoom',()=>{const c=new Camera(1536,864);c.fit(1100,800);const p={x:.32,y:.79};const screen=c.toScreen(p);expect(c.toProject(screen).x).toBeCloseTo(p.x);c.zoom(2,screen);expect(c.toScreen(p).x).toBeCloseTo(screen.x);expect(c.toScreen(p).y).toBeCloseTo(screen.y);c.pan(10,-20);expect(c.toScreen(p).x).toBeCloseTo(screen.x+10);c.fit(800,600);expect(c.toProject(c.toScreen(p)).y).toBeCloseTo(p.y);});
 test('normalized bounds, hit testing and motion vectors',()=>{expect(clamp({x:-1,y:2})).toEqual({x:0,y:1});expect(bounds(ann).x).toBeCloseTo(.19);expect(bounds(ann).bottom).toBeCloseTo(.61);expect(hit(ann,{x:.21,y:.3})).toBe(true);expect(hit(ann,{x:0,y:0})).toBe(false);expect(motion(ann).dx).toBeCloseTo(.5);});
});
describe('queue and composition',()=>{
 test('dependent requests execute sequentially',async()=>{const q=new GenerationQueue(),order:number[]=[];const a=q.enqueue(async()=>{await Bun.sleep(15);order.push(1);return 1;});const b=q.enqueue(async()=>{order.push(2);return 2;});expect(await Promise.all([a,b])).toEqual([1,2]);expect(order).toEqual([1,2]);});
 test('cancellation stops queued work and rejects late responses',async()=>{const q=new GenerationQueue();let release:()=>void=()=>{};let invoked=false;const started=new Promise<void>(r=>release=r);const a=q.enqueue(async signal=>{release();await Bun.sleep(20);return signal.aborted?'aborted':'result';});const b=q.enqueue(async()=>{invoked=true;return 2;});const results=Promise.allSettled([a,b]);await started;q.cancel();expect((await results).every(r=>r.status==='rejected')).toBe(true);expect(invoked).toBe(false);expect(await q.enqueue(async()=>3)).toBe(3);});
 test('repair prompt preserves current pose and includes normalized motion and scene constraints',()=>{const p=newProject();p.annotations.draft=[ann,{...ann,kind:'comment',text:'Keep eyes round'}];p.sceneBible='Blue robot, amber eyes';const prompt=compose(p,{prompt:'Restore eyes',profile:'PRECISE',quality:'high',sourceId:'target-pose',repair:true});expect(prompt).toContain('preserving its current pose');expect(prompt).toContain('Keep eyes round');expect(prompt).toContain('Blue robot');expect(prompt).toContain('0.7');});
});
describe('input boundaries',()=>{
 test('valid image request and invalid dimensions / profile / remote URL',()=>{const raw={prompt:'robot',width:1024,height:1024,modelProfile:'FAST'};expect(validateImageRequest(raw,false).quality).toBe('medium');expect(()=>validateImageRequest({...raw,width:1000},false)).toThrow();expect(()=>validateImageRequest({...raw,modelProfile:'secret'},false)).toThrow();expect(()=>validateImageRequest({...raw,images:['https://example.com/image.png']},true)).toThrow();expect(()=>validateImageRequest(raw,true)).toThrow();expect(()=>validateImageRequest({...raw,images:['data:image/png;base64,YWJj']},true)).toThrow();});
 test('motion plan validates count, order and instructions',()=>{const plan={frames:[{index:1,instruction:'Move arm slightly'}]};expect(validatePlan(plan,1)).toBe(plan);expect(()=>validatePlan(plan,2)).toThrow();expect(()=>validatePlan({frames:[{index:2,instruction:'move'}]},1)).toThrow();expect(()=>validatePlan({frames:[{index:1,instruction:''}]},1)).toThrow();});
});

test('motion annotations stay attached to every request in a batch',()=>{const p=newProject();const snapshot=[ann];const before=compose(p,{prompt:'Move right',profile:'FAST',quality:'low',annotationSnapshot:snapshot});addRevision(p,asset(),'next');const after=compose(p,{prompt:'Move right',profile:'FAST',quality:'low',annotationSnapshot:snapshot});expect(before).toContain('Motion arrows');expect(after).toContain('Motion arrows');});
test('imported identifiers cannot inject markup into project controls',()=>{const p=newProject();p.id='" onclick="alert(1)';expect(()=>migrateProject(p)).toThrow('Invalid project metadata');});
