export type Lang = 'en' | 'es';
export type Text = { en: string; es: string };
export const bi = (en: string, es: string): Text => ({ en, es });
export type Card = { id: string; name: Text; theme: Text; meaning: Text; advice: Text; reversed: Text; suit: string };
const majorRows = [
['fool','The Fool','El Loco','Beginnings','Comienzos','A new experience asks for curiosity and a willingness to learn as you go.','Una nueva experiencia pide curiosidad y disposición para aprender sobre la marcha.','Take one small step into the unfamiliar.','Da un pequeño paso hacia lo desconocido.'],
['magician','The Magician','El Mago','Intention','Intención','You have tools and abilities that can turn an idea into something tangible. Focus gives them direction.','Tienes herramientas y capacidades para convertir una idea en algo tangible. El enfoque les da dirección.','Choose one idea and put your skills to work.','Elige una idea y pon tus habilidades en práctica.'],
['high-priestess','The High Priestess','La Sacerdotisa','Intuition','Intuición','Not everything is visible yet. Quiet observation can reveal what urgency would overlook.','Aún no todo es visible. La observación tranquila puede revelar lo que las prisas pasan por alto.','Listen inward, then check your impressions against the facts.','Escucha tu interior y contrasta tus impresiones con los hechos.'],
['empress','The Empress','La Emperatriz','Nurturing','Cuidado','Growth comes through care, creativity, and attention to the conditions that allow life to flourish.','El crecimiento nace del cuidado, la creatividad y las condiciones que permiten florecer.','Give consistent care to something you want to grow.','Cuida con constancia algo que quieras ver crecer.'],
['emperor','The Emperor','El Emperador','Structure','Estructura','Clear boundaries and dependable plans create a foundation for confident action.','Los límites claros y los planes fiables crean una base para actuar con confianza.','Build a routine that supports your priorities.','Crea una rutina que apoye tus prioridades.'],
['hierophant','The Hierophant','El Sumo Sacerdote','Wisdom','Sabiduría','Tradition, shared knowledge, or a trusted mentor can offer a useful framework.','La tradición, el conocimiento compartido o una persona de confianza pueden ofrecer una guía útil.','Seek guidance while leaving room for your own judgment.','Busca orientación sin renunciar a tu propio criterio.'],
['lovers','The Lovers','Los Enamorados','Alignment','Afinidad','Relationships and meaningful choices invite you to act in agreement with your values.','Las relaciones y las decisiones importantes te invitan a actuar de acuerdo con tus valores.','Make the choice you can stand behind honestly.','Elige aquello que puedas defender con honestidad.'],
['chariot','The Chariot','El Carro','Direction','Dirección','Progress requires coordinating competing impulses and choosing where to direct your energy.','El progreso requiere coordinar impulsos opuestos y decidir hacia dónde dirigir tu energía.','Name your destination before increasing your pace.','Define tu destino antes de acelerar.'],
['strength','Strength','La Fuerza','Courage','Valentía','Patient courage and self-compassion can accomplish what force cannot.','La valentía paciente y la autocompasión pueden lograr lo que la fuerza bruta no consigue.','Respond firmly and gently to the next challenge.','Responde con firmeza y amabilidad al próximo reto.'],
['hermit','The Hermit','El Ermitaño','Reflection','Reflexión','A little distance from noise can help you hear your own perspective and recover a sense of purpose.','Tomar distancia del ruido puede ayudarte a escuchar tu perspectiva y recuperar el propósito.','Set aside quiet time for a question that matters.','Reserva un momento de calma para una pregunta importante.'],
['wheel-of-fortune','Wheel of Fortune','La Rueda de la Fortuna','Cycles','Ciclos','Circumstances change. Recognizing what you can influence helps you respond to a turning point.','Las circunstancias cambian. Reconocer en qué puedes influir te ayuda a responder a un giro.','Adapt your plan to what is actually happening.','Adapta tu plan a lo que está ocurriendo.'],
['justice','Justice','La Justicia','Accountability','Responsabilidad','Fairness asks you to look at evidence, consequences, and your part in the situation.','La justicia te pide observar las pruebas, las consecuencias y tu papel en la situación.','Choose a fair action and accept responsibility for it.','Elige una acción justa y asume su responsabilidad.'],
['hanged-man','The Hanged Man','El Colgado','Perspective','Perspectiva','A pause may offer a new angle when pushing ahead has stopped being useful.','Una pausa puede ofrecer otro ángulo cuando insistir ya no resulta útil.','Try looking at the situation from another person’s position.','Intenta mirar la situación desde la posición de otra persona.'],
['death','Death','La Muerte','Transformation','Transformación','An ending can clear space for change. This symbol concerns transition and letting go, not literal death.','Un final puede abrir espacio al cambio. Este símbolo habla de transición y soltar, no de muerte literal.','Release one habit or expectation that has run its course.','Suelta un hábito o una expectativa que haya cumplido su ciclo.'],
['temperance','Temperance','La Templanza','Balance','Equilibrio','Different needs can find a sustainable rhythm through patience and thoughtful adjustment.','Necesidades distintas pueden encontrar un ritmo sostenible con paciencia y ajustes conscientes.','Choose a manageable middle path.','Elige un camino intermedio que puedas mantener.'],
['devil','The Devil','El Diablo','Attachments','Ataduras','A habit, temptation, or limiting belief may be reducing your sense of choice.','Un hábito, una tentación o una creencia limitante pueden reducir tu sensación de libertad.','Notice one pattern you are ready to interrupt.','Reconoce un patrón que estés dispuesto a interrumpir.'],
['tower','The Tower','La Torre','Revelation','Revelación','An assumption may need to change. Honest reassessment can help you rebuild on firmer ground.','Quizá una suposición deba cambiar. Una revisión honesta puede ayudarte a reconstruir sobre una base más firme.','Check your foundations before rebuilding your plans.','Revisa tus bases antes de reconstruir tus planes.'],
['star','The Star','La Estrella','Renewal','Renovación','After difficulty, a quiet sense of possibility can return. Hope grows with realistic, restorative action.','Tras una dificultad puede volver una tranquila sensación de posibilidad. La esperanza crece con acciones realistas y reparadoras.','Make room for something that restores your energy.','Haz espacio para algo que renueve tu energía.'],
['moon','The Moon','La Luna','Uncertainty','Incertidumbre','Imagination and emotion are vivid, but the full picture may be unclear. Uncertainty deserves patience.','La imaginación y las emociones son intensas, pero quizá falte claridad. La incertidumbre merece paciencia.','Separate what you know from what you fear or assume.','Separa lo que sabes de lo que temes o supones.'],
['sun','The Sun','El Sol','Clarity','Claridad','Warmth, openness, and simple enjoyment can illuminate what is working in your life.','La calidez, la apertura y el disfrute sencillo pueden iluminar lo que funciona en tu vida.','Acknowledge progress and share something honestly.','Reconoce tus avances y comparte algo con honestidad.'],
['judgement','Judgement','El Juicio','Awakening','Despertar','Looking back with honesty can help you answer a renewed sense of purpose.','Mirar atrás con honestidad puede ayudarte a responder a un propósito renovado.','Take a lesson from the past into your next decision.','Lleva una lección del pasado a tu próxima decisión.'],
['world','The World','El Mundo','Completion','Plenitud','A cycle is coming together. Integration means recognizing what you have learned before moving on.','Un ciclo toma forma. Integrar significa reconocer lo aprendido antes de seguir adelante.','Celebrate a milestone and give it a thoughtful ending.','Celebra un hito y dale un cierre consciente.'],
];
export const cards: Card[] = majorRows.map(r => ({id:r[0]!,name:bi(r[1]!,r[2]!),theme:bi(r[3]!,r[4]!),meaning:bi(r[5]!,r[6]!),advice:bi(r[7]!,r[8]!),reversed:bi(`Consider where ${r[3]!.toLowerCase()} feels blocked, excessive, or turned inward. ${r[7]}`,`Observa dónde el tema de ${r[4]!.toLowerCase()} se siente bloqueado, excesivo o interiorizado. ${r[8]}`),suit:'major'}));
const ranks = ['ace','two','three','four','five','six','seven','eight','nine','ten','page','knight','queen','king'];
const rankNames = ['As','Dos','Tres','Cuatro','Cinco','Seis','Siete','Ocho','Nueve','Diez','Sota','Caballero','Reina','Rey'];
const suitData = [
{ id:'wands',es:'Bastos',area:bi('creativity, motivation, and action','la creatividad, la motivación y la acción'),themes:['Inspiration|Inspiración','Planning|Planificación','Expansion|Expansión','Celebration|Celebración','Competition|Competencia','Recognition|Reconocimiento','Conviction|Convicción','Momentum|Impulso','Resilience|Resiliencia','Burden|Carga','Discovery|Descubrimiento','Adventure|Aventura','Confidence|Confianza','Leadership|Liderazgo'],advice:[['Act on a fresh spark while it is still small.','Actúa sobre una nueva chispa mientras aún es pequeña.'],['Compare your options before committing energy.','Compara tus opciones antes de comprometer tu energía.'],['Look beyond familiar territory for your next opportunity.','Mira más allá de lo conocido para encontrar tu próxima oportunidad.'],['Pause to enjoy what you have built with others.','Detente a disfrutar de lo que has construido con otras personas.'],['Channel disagreement into useful collaboration.','Transforma el desacuerdo en colaboración útil.'],['Accept recognition and credit those who helped.','Acepta el reconocimiento y agradece a quienes ayudaron.'],['Protect a priority without treating every challenge as a threat.','Protege una prioridad sin ver cada reto como una amenaza.'],['Prepare to respond as several things begin to move.','Prepárate para responder cuando varias cosas empiecen a avanzar.'],['Rest without abandoning what matters to you.','Descansa sin abandonar lo que te importa.'],['Put down or delegate a responsibility that is not yours alone.','Suelta o delega una responsabilidad que no sea solo tuya.'],['Explore an interest before demanding mastery of yourself.','Explora un interés sin exigirte dominarlo de inmediato.'],['Give enthusiasm a direction and check the practical details.','Da dirección al entusiasmo y comprueba los detalles prácticos.'],['Trust your ability to encourage and create.','Confía en tu capacidad de animar y crear.'],['Lead with a clear vision and room for others to contribute.','Lidera con una visión clara y espacio para las aportaciones de otros.']]},
{ id:'cups',es:'Copas',area:bi('feelings, connection, and emotional needs','los sentimientos, los vínculos y las necesidades emocionales'),themes:['Openness|Apertura','Partnership|Unión','Friendship|Amistad','Contemplation|Contemplación','Disappointment|Decepción','Memory|Recuerdos','Possibilities|Posibilidades','Departure|Partida','Contentment|Satisfacción','Belonging|Pertenencia','Sensitivity|Sensibilidad','Invitation|Invitación','Empathy|Empatía','Composure|Serenidad'],advice:[['Allow yourself to receive care or express a feeling.','Permítete recibir cuidado o expresar un sentimiento.'],['Make space for an honest, reciprocal conversation.','Haz espacio para una conversación honesta y recíproca.'],['Reconnect with people who make you feel supported.','Reconecta con personas que te hacen sentir acompañado.'],['Notice an offer you might be overlooking.','Observa una propuesta que quizá estés pasando por alto.'],['Honor disappointment while noticing what remains.','Respeta tu decepción y observa lo que todavía permanece.'],['Take comfort from the past without trying to live in it.','Encuentra consuelo en el pasado sin intentar vivir en él.'],['Test one possibility instead of getting lost in many.','Prueba una posibilidad en lugar de perderte entre muchas.'],['Ask whether an attachment still nourishes you.','Pregúntate si un vínculo aún te nutre.'],['Appreciate a present comfort without requiring perfection.','Aprecia un bienestar presente sin exigir perfección.'],['Invest in the relationships that make belonging possible.','Cuida las relaciones que hacen posible la pertenencia.'],['Meet a new feeling with curiosity and gentleness.','Recibe un nuevo sentimiento con curiosidad y ternura.'],['Express a heartfelt intention with realistic expectations.','Expresa una intención sincera con expectativas realistas.'],['Care for another person without absorbing all their feelings.','Cuida a otra persona sin absorber todas sus emociones.'],['Hold strong feelings with patience before responding.','Acoge las emociones intensas con paciencia antes de responder.']]},
{ id:'swords',es:'Espadas',area:bi('thoughts, communication, and decisions','los pensamientos, la comunicación y las decisiones'),themes:['Truth|Verdad','Indecision|Indecisión','Heartache|Dolor','Rest|Descanso','Conflict|Conflicto','Transition|Transición','Strategy|Estrategia','Restriction|Restricción','Worry|Preocupación','Ending|Final','Inquiry|Indagación','Determination|Determinación','Discernment|Discernimiento','Reason|Razón'],advice:[['Put a difficult truth into clear, simple words.','Expresa una verdad difícil con palabras claras y sencillas.'],['Identify the information you need to make a choice.','Identifica la información que necesitas para elegir.'],['Name a hurt and seek a constructive way to process it.','Nombra una herida y busca una manera constructiva de procesarla.'],['Give your mind time away from a demanding problem.','Dale a tu mente tiempo lejos de un problema exigente.'],['Consider whether winning this argument would be worth its cost.','Considera si ganar esta discusión compensaría su coste.'],['Accept support as you move away from a difficult situation.','Acepta apoyo al alejarte de una situación difícil.'],['Be strategic while staying honest about your intentions.','Actúa con estrategia y honestidad sobre tus intenciones.'],['Check which limits are fixed and which could be questioned.','Comprueba qué límites son fijos y cuáles podrías cuestionar.'],['Write down a worry and distinguish evidence from speculation.','Escribe una preocupación y distingue las pruebas de las suposiciones.'],['Let an exhausted approach end before choosing the next one.','Deja que termine un enfoque agotado antes de elegir el siguiente.'],['Ask a precise question and be willing to learn.','Haz una pregunta precisa y mantén la disposición a aprender.'],['Check your facts before speaking or acting at speed.','Comprueba los hechos antes de hablar o actuar con rapidez.'],['Set a clear boundary with honesty and consideration.','Establece un límite claro con honestidad y consideración.'],['Use sound reasoning without dismissing the human context.','Usa un razonamiento sólido sin descuidar el contexto humano.']]},
{ id:'pentacles',es:'Oros',area:bi('work, resources, and everyday stability','el trabajo, los recursos y la estabilidad cotidiana'),themes:['Opportunity|Oportunidad','Adaptability|Adaptabilidad','Craft|Oficio','Security|Seguridad','Hardship|Dificultad','Generosity|Generosidad','Patience|Paciencia','Practice|Práctica','Independence|Independencia','Legacy|Legado','Learning|Aprendizaje','Consistency|Constancia','Practical care|Cuidado práctico','Stewardship|Administración'],advice:[['Turn an opportunity into one practical first step.','Convierte una oportunidad en un primer paso práctico.'],['Adjust your commitments to the resources you actually have.','Ajusta tus compromisos a los recursos que tienes.'],['Invite feedback and build on complementary skills.','Pide opiniones y aprovecha habilidades complementarias.'],['Balance protecting your resources with allowing them to be useful.','Equilibra la protección de tus recursos con permitir que sean útiles.'],['Look for available help rather than struggling in isolation.','Busca la ayuda disponible en lugar de afrontar todo en soledad.'],['Notice whether giving and receiving feel fair.','Observa si dar y recibir se sienten equilibrados.'],['Review what your effort is producing before investing more.','Revisa lo que produce tu esfuerzo antes de invertir más.'],['Improve one skill through steady, attentive repetition.','Mejora una habilidad con repetición constante y atenta.'],['Recognize the freedom your patient effort has created.','Reconoce la libertad que ha creado tu esfuerzo paciente.'],['Consider what you want to sustain beyond the immediate moment.','Considera qué deseas mantener más allá del momento inmediato.'],['Begin learning with a modest, concrete goal.','Empieza a aprender con una meta modesta y concreta.'],['Keep a useful promise through consistent small actions.','Cumple una promesa útil con pequeñas acciones constantes.'],['Make daily life more supportive for yourself and others.','Haz que la vida cotidiana te cuide más a ti y a los demás.'],['Manage resources with care for long-term stability.','Administra los recursos cuidando la estabilidad a largo plazo.']]},
];
for (const suit of suitData) ranks.forEach((rank,i) => {const theme=suit.themes[i]!.split('|');const advice=suit.advice[i]!; cards.push({id:`${rank}-of-${suit.id}`,name:bi(`${rank[0]!.toUpperCase()+rank.slice(1)} of ${suit.id[0]!.toUpperCase()+suit.id.slice(1)}`,`${rankNames[i]} de ${suit.es}`),theme:bi(theme[0]!,theme[1]!),meaning:bi(`This card brings ${theme[0]!.toLowerCase()} into focus in ${suit.area.en}. ${advice[0]}`,`Esta carta destaca el tema de ${theme[1]!.toLowerCase()} en ${suit.area.es}. ${advice[1]}`),advice:bi(advice[0]!,advice[1]!),reversed:bi(`Notice where ${theme[0]!.toLowerCase()} is delayed, overextended, or needs inward attention. ${advice[0]}`,`Observa dónde el tema de ${theme[1]!.toLowerCase()} se retrasa, se excede o necesita atención interior. ${advice[1]}`),suit:suit.id});});
export type Deck = {id:string; name:Text; description:Text; files:Record<string,string>; overrides?:Record<string,Partial<Card>>};
export type Position = {name:Text; description:Text};
const pos=(en:string,es:string,a:string,b:string):Position=>({name:bi(en,es),description:bi(a,b)});
export const spreads = [
{id:'three',name:bi('Past, Present & Future','Pasado, presente y futuro'),short:bi('The three-card spread','La tirada de tres cartas'),description:bi('Trace the thread from where you have been to where you could go. A little perspective for the path ahead.','Sigue el hilo de donde vienes hacia donde podrías ir. Una nueva perspectiva para el camino que tienes delante.'),time:bi('3–5 min','3–5 min'),positions:[pos('Past','Pasado','The experiences and patterns that brought you here.','Las experiencias y los patrones que te han traído hasta aquí.'),pos('Present','Presente','The energy and choices around you right now.','La energía y las decisiones que te rodean ahora.'),pos('Future','Futuro','A possible direction if current patterns continue.','Una dirección posible si los patrones actuales continúan.')]},
{id:'daily',name:bi('Daily Reflection','Reflexión diaria'),short:bi('The one-card ritual','El ritual de una carta'),description:bi('One card. A quiet moment. Discover a theme to carry with you through the day.','Una carta. Un momento de calma. Descubre un tema para acompañarte durante el día.'),time:bi('1–2 min','1–2 min'),positions:[pos('Your guiding card','Tu carta guía','An invitation to focus your attention today.','Una invitación para orientar tu atención hoy.')]},
{id:'path',name:bi('The Path Forward','El camino a seguir'),short:bi('The five-card spread','La tirada de cinco cartas'),description:bi('Look at a situation from five angles, uncover what supports you, and find a considered next step.','Mira una situación desde cinco ángulos, descubre tus apoyos y encuentra un próximo paso consciente.'),time:bi('5–8 min','5–8 min'),positions:[pos('Situation','Situación','The central theme of your question.','El tema central de tu pregunta.'),pos('Challenge','Reto','Something to acknowledge or work through.','Algo que reconocer o afrontar.'),pos('Support','Apoyo','A resource or strength available to you.','Un recurso o una fortaleza a tu alcance.'),pos('Advice','Consejo','A constructive approach worth exploring.','Un enfoque constructivo que vale la pena explorar.'),pos('Potential','Potencial','What this approach might make possible.','Lo que este enfoque podría hacer posible.')]},
{id:'celtic',name:bi('The Celtic Cross','La cruz celta'),short:bi('The ten-card spread','La tirada de diez cartas'),description:bi('A deeper exploration of your inner world, outside influences, and the possibilities taking shape.','Una exploración de tu mundo interior, las influencias externas y las posibilidades que toman forma.'),time:bi('10–15 min','10–15 min'),positions:[pos('The heart','El centro','What is at the center of your situation.','Lo que ocupa el centro de tu situación.'),pos('The crossing','El cruce','A tension that challenges or complements the first card.','Una tensión que desafía o complementa la primera carta.'),pos('Foundation','La raíz','The underlying pattern beneath the surface.','El patrón de fondo bajo la superficie.'),pos('Recent past','Pasado reciente','An influence you are moving away from.','Una influencia de la que te estás alejando.'),pos('Possibility','Posibilidad','A conscious aspiration or available perspective.','Una aspiración consciente o una perspectiva disponible.'),pos('Near future','Futuro cercano','A possible next development, not a fixed prediction.','Un posible próximo desarrollo, no una predicción fija.'),pos('Your approach','Tu actitud','The attitude you bring to this question.','La actitud que aportas a esta pregunta.'),pos('Environment','El entorno','The people and circumstances around you.','Las personas y las circunstancias que te rodean.'),pos('Hopes & fears','Deseos y temores','A wish or worry coloring your perception.','Un deseo o un temor que influye en tu percepción.'),pos('Potential outcome','Resultado potencial','A direction to reflect on alongside all the other cards.','Una dirección sobre la que reflexionar junto a las demás cartas.')]},
];
export type Drawn = {id:string; reversed:boolean};
export function drawCards(count:number, reversals:boolean, random=()=>crypto.getRandomValues(new Uint32Array(1))[0]!/4294967296):Drawn[]{
 if(!Number.isInteger(count)||count<1||count>cards.length) throw new Error('Invalid card count');
 const pool=cards.map(c=>c.id);for(let i=pool.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[pool[i],pool[j]]=[pool[j]!,pool[i]!];}return pool.slice(0,count).map(id=>({id,reversed:reversals&&random()<.3}));
}
export function getCard(id:string,deck?:Deck):Card{const base=cards.find(c=>c.id===id);if(!base)throw new Error('Unknown card');return {...base,...deck?.overrides?.[id]};}
export const cardImage=(deck:Deck,id:string)=>`/decks/${deck.id}/${deck.files[id]}`;
