import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,BookOpen,Check,ChevronDown,ChevronRight,Layers3,RotateCcw,Shuffle,Sparkles,Sun, X, MoveUpRight, CircleHelp,ZoomIn} from 'lucide-react';
import CardTable from './CardTable';
import {useTarotTools} from './webmcp';
import {ThemeSelector, useTheme} from './themes';
import {createCardBack} from './cardBack';
import {useCardInspection, type CardPreview} from './CardInspection';
import {bi,spreads,drawCards,getCard,cardImage,type Deck,type Drawn,type Lang} from './data';
const copy={
 en:{room:'Reading room',decks:'The decks',guide:'A little guidance',eyebrow:'A MOMENT BETWEEN YOU & THE UNIVERSE',title:'The answers lie',italic:'within.',intro:'Quiet your mind. Ask a question. Let the cards tell their story.',spread:'YOUR SPREAD',choose:'Choose your perspective',deck:'YOUR DECK',change:'Explore decks',intention:'What is on your mind?',optional:'OPTIONAL',placeholder:'A question, an intention, or simply an open mind…',reversals:'Include reversed cards',reversalHint:'Explore the other side of each card',ritual:'YOUR READING',reveal:'Reveal my cards',revealAll:'Reveal remaining cards',shuffle:'Shuffle cards',newReading:'New reading',hint:'Take a breath. Choose a card when you feel ready.',revealed:'cards revealed',complete:'Your reading is complete',selected:'THE CARD & ITS MEANING',upright:'Upright',reversed:'Reversed',inPosition:'IN THIS POSITION',invitation:'AN INVITATION',outcome:'The story of your spread',outcomeLabel:'YOUR REFLECTION',outcomeIntro:'Read these cards as a conversation:',outcomeClose:'This is a possibility to reflect on, shaped by your choices—not a fixed prediction.',emptyTitle:'Every card has a story.',emptyText:'Turn a card to discover its meaning and the part it plays in your reading.',footer:'A mirror for reflection. A moment for yourself.',footnote:'The future is yours to create.',select:'Select deck',active:'In your reading',deckTitle:'A different language of symbols.',deckIntro:'The same ritual, seen through a different lens. Change decks at any time.',guideTitle:'Make space for a little wonder.',guideIntro:'Tarot is a practice of reflection. There is no perfect question, and no single right way to read a card.',guideSteps:[['01','Set an intention','Ask an open question, such as “What could help me move forward?” Or leave the question empty and see what resonates.'],['02','Choose your spread','One card offers a daily focus. Three explore time. Five illuminate a path. The Celtic Cross offers ten connected perspectives.'],['03','Turn the cards','Touch a card to turn it over. Select its name below the table to revisit the interpretation. You can also reveal all cards together.'],['04','Find your own meaning','Upright cards express a theme directly; reversed cards invite reflection on a blocked, excessive, or inward expression. Read the outcome as a prompt, never a certainty.']],historic:'The artwork keeps its original language. Card titles and all readings are available in English and Spanish. Etteilla uses its own card identities and modern image-inspired reflections.',loading:'Preparing the reading room…',error:'The decks could not be loaded.',retry:'Try again',context:'Your intention',potential:'A possible next step',return:'Back to the reading',tip:'Let your intuition choose.'},
 es:{room:'Sala de lectura',decks:'Las barajas',guide:'Un poco de orientación',eyebrow:'UN MOMENTO ENTRE TÚ Y EL UNIVERSO',title:'Las respuestas están',italic:'dentro.',intro:'Aquieta la mente. Haz una pregunta. Deja que las cartas cuenten su historia.',spread:'TU TIRADA',choose:'Elige tu perspectiva',deck:'TU BARAJA',change:'Explorar barajas',intention:'¿Qué tienes en mente?',optional:'OPCIONAL',placeholder:'Una pregunta, una intención o simplemente una mente abierta…',reversals:'Incluir cartas invertidas',reversalHint:'Explora el otro lado de cada carta',ritual:'TU LECTURA',reveal:'Revelar mis cartas',revealAll:'Revelar las cartas restantes',shuffle:'Barajar cartas',newReading:'Nueva lectura',hint:'Respira. Elige una carta cuando estés preparado.',revealed:'cartas reveladas',complete:'Tu lectura está completa',selected:'LA CARTA Y SU SIGNIFICADO',upright:'Al derecho',reversed:'Invertida',inPosition:'EN ESTA POSICIÓN',invitation:'UNA INVITACIÓN',outcome:'La historia de tu tirada',outcomeLabel:'TU REFLEXIÓN',outcomeIntro:'Lee estas cartas como una conversación:',outcomeClose:'Es una posibilidad para reflexionar, moldeada por tus decisiones, no una predicción fija.',emptyTitle:'Cada carta tiene una historia.',emptyText:'Da la vuelta a una carta para descubrir su significado y su papel en tu lectura.',footer:'Un espejo para reflexionar. Un momento para ti.',footnote:'El futuro lo creas tú.',select:'Elegir baraja',active:'En tu lectura',deckTitle:'Otro lenguaje de símbolos.',deckIntro:'El mismo ritual, visto desde otra perspectiva. Cambia de baraja cuando quieras.',guideTitle:'Haz espacio para la curiosidad.',guideIntro:'El tarot es una práctica de reflexión. No hay una pregunta perfecta ni una única forma correcta de leer una carta.',guideSteps:[['01','Define una intención','Haz una pregunta abierta, como «¿Qué podría ayudarme a avanzar?». O deja la pregunta vacía y observa qué resuena contigo.'],['02','Elige tu tirada','Una carta ofrece un enfoque diario. Tres exploran el tiempo. Cinco iluminan un camino. La cruz celta ofrece diez perspectivas conectadas.'],['03','Da la vuelta a las cartas','Toca una carta para girarla. Selecciona su nombre bajo la mesa para volver a su interpretación. También puedes revelar todas juntas.'],['04','Encuentra tu significado','Las cartas al derecho expresan un tema directamente; las invertidas invitan a reflexionar sobre una expresión bloqueada, excesiva o interior. El resultado es una sugerencia, nunca una certeza.']],historic:'Las imágenes conservan su idioma original. Los títulos y las lecturas están en inglés y español. Etteilla utiliza sus propias identidades y reflexiones modernas inspiradas en sus imágenes.',loading:'Preparando la sala de lectura…',error:'No se han podido cargar las barajas.',retry:'Intentar de nuevo',context:'Tu intención',potential:'Un posible próximo paso',return:'Volver a la lectura',tip:'Deja que tu intuición elija.'}
};
function SpreadIcon({count}:{count:number}){return <span className={`spread-icon icon-${count}`} aria-hidden="true">{Array.from({length:count===10?5:count},(_,i)=><i key={i}/>)}</span>}
function Seal({small=false}:{small?:boolean}){return <span className={`seal ${small?'small':''}`} aria-hidden="true"><Sun size={small?22:32} strokeWidth={1}/></span>}
function Modal({children,onClose,label}:{children:React.ReactNode;onClose:()=>void;label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current!;d.showModal();return()=>d.close()},[]);return <dialog ref={ref} className="modal" aria-label={label} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><button className="close-modal icon-button" onClick={onClose} aria-label={document.documentElement.lang==='es'?'Cerrar':'Close'}><X size={22}/></button>{children}</dialog>}
function App(){
 const [lang,setLang]=useState<Lang>(()=>{try{return localStorage.getItem('arcana-lang')==='es'?'es':'en'}catch{return 'en'}});const t=copy[lang];
 const [theme,setTheme]=useTheme();
 const inspection=useCardInspection(lang);
 const [decks,setDecks]=useState<Deck[]>([]);const [deckId,setDeckId]=useState('rider-waite-tarot');const [spreadId,setSpreadId]=useState('three');const spread=spreads.find(s=>s.id===spreadId)!;
 const [reversals,setReversals]=useState(false);const [question,setQuestion]=useState('');const [drawn,setDrawn]=useState<Drawn[]>(()=>drawCards(3,false));const [revealed,setRevealed]=useState<boolean[]>([false,false,false]);const [selected,setSelected]=useState(0);const [readingKey,setReadingKey]=useState(0);const [modal,setModal]=useState<'decks'|'guide'|null>(null);const [error,setError]=useState(false);const [revealing,setRevealing]=useState(false);const timers=useRef<ReturnType<typeof setTimeout>[]>([]);
 const deck=decks.find(d=>d.id===deckId)||decks[0];const count=revealed.filter(Boolean).length;const all=count===drawn.length;const active=deck&&drawn[selected]?getCard(drawn[selected]!.id,deck):null;

 useTarotTools({count:()=>drawn.length,reveal:indices=>{cancelReveal();setRevealed(prev=>prev.map((v,i)=>v||indices.includes(i)));setSelected(indices.at(-1)!);},read:()=>({language:lang,deck:deck?.name[lang],spread:spread.name[lang],complete:all,cards:drawn.map((d,i)=>{const c=getCard(d.id,deck);return {position:spread.positions[i]!.name[lang],revealed:revealed[i],...(revealed[i]?{name:c.name[lang],reversed:d.reversed,meaning:d.reversed?c.reversed[lang]:c.meaning[lang],positionMeaning:spread.positions[i]!.description[lang],advice:c.advice[lang]}:{})};})})});
 async function loadDecks(){setError(false);try{const r=await fetch('/decks.json');if(!r.ok)throw new Error();const d=await r.json();if(!Array.isArray(d)||!d.length)throw new Error();setDecks(d);}catch{setError(true)}}
 useEffect(()=>{loadDecks();return()=>timers.current.forEach(clearTimeout)},[]);
 useEffect(()=>{document.documentElement.lang=lang;try{localStorage.setItem('arcana-lang',lang)}catch{}},[lang]);
 function previewCard(index:number):CardPreview {
  const card=drawn[index]!;
  return revealed[index]?{image:cardImage(deck!,card.id),name:getCard(card.id,deck).name[lang],reversed:card.reversed}:{image:createCardBack(theme).toDataURL('image/png'),name:lang==='en'?'Card back':'Reverso de la carta',reversed:false};
 }
 function cancelReveal(){timers.current.forEach(clearTimeout);timers.current=[];setRevealing(false)}
 function reset(id=spreadId,rev=reversals){cancelReveal();const s=spreads.find(s=>s.id===id)!;setDrawn(drawCards(s.positions.length,rev));setRevealed(s.positions.map(()=>false));setSelected(0);setReadingKey(k=>k+1)}
 function changeSpread(id:string){if(id===spreadId)return;setSpreadId(id);reset(id)}
 function flip(i:number){if(revealing)return;setRevealed(prev=>prev.map((v,j)=>j===i?!v:v));setSelected(i)}
 function revealAll(){if(revealing)return;const hidden=revealed.map((v,i)=>v?-1:i).filter(i=>i>=0);setRevealing(true);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;hidden.forEach((index,n)=>{timers.current.push(setTimeout(()=>{setRevealed(prev=>prev.map((v,i)=>i===index?true:v));setSelected(index);if(n===hidden.length-1)setRevealing(false)},reduced?0:n*350));});}
 return <div className="app-shell">
 <header className="header"><a href="#" className="brand" aria-label="Arcana" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})}}><Seal/><span>ARCANA<small>{lang==='en'?'THE ART OF INTUITION':'EL ARTE DE LA INTUICIÓN'}</small></span></a><nav aria-label={lang==='en'?'Main navigation':'Navegación principal'}><button className={!modal?'nav-active':''} onClick={()=>setModal(null)}>{t.room}</button><button className={modal==='decks'?'nav-active':''} onClick={()=>setModal('decks')}>{t.decks}</button><button className={modal==='guide'?'nav-active':''} onClick={()=>setModal('guide')}>{t.guide}<ArrowUpRight size={14}/></button></nav><div className="header-controls"><div className="language" aria-label="Language / Idioma"><button aria-pressed={lang==='en'} onClick={()=>setLang('en')}>EN</button><span>/</span><button aria-pressed={lang==='es'} onClick={()=>setLang('es')}>ES</button></div><ThemeSelector theme={theme} onChange={setTheme} lang={lang}/></div></header>
 <main>
 <section className="intro"><div className="eyebrow"><span/> {t.eyebrow} <span/></div><h1>{t.title} <em>{t.italic}</em></h1><p>{t.intro}</p><div className="intro-stars" aria-hidden="true">✧</div></section>
 {!deck?<div className="loading-panel"><Seal/><p>{error?t.error:t.loading}</p>{error&&<button className="gold-button" onClick={loadDecks}>{t.retry}</button>}</div>:<div className="reading-layout">
 <aside className="sidebar"><div className="section-label"><span>01</span>{t.spread}</div><h2>{t.choose}</h2><div className="spread-list">{spreads.map(s=><button key={s.id} className={`spread-option ${s.id===spreadId?'active':''}`} onClick={()=>changeSpread(s.id)} aria-pressed={s.id===spreadId}><SpreadIcon count={s.positions.length}/><span><strong>{s.name[lang]}</strong><small>{s.positions.length} {lang==='en'?(s.positions.length===1?'card':'cards'):(s.positions.length===1?'carta':'cartas')}<i/> {s.time[lang]}</small></span>{s.id===spreadId?<span className="selected-dot"/>:<ChevronRight className="spread-arrow" size={15}/>}</button>)}</div>
 <div className="deck-section"><div className="section-label"><span>02</span>{t.deck}</div><button className="deck-preview" onClick={()=>setModal('decks')} aria-label={t.change}><span className="deck-fan"><img src={cardImage(deck,'moon')} alt=""/><img src={cardImage(deck,'star')} alt=""/><img src={cardImage(deck,'sun')} alt=""/></span><span className="deck-preview-name">{deck.name[lang]}<small>78 {lang==='en'?'cards · a world of symbols':'cartas · un mundo de símbolos'}</small></span><span className="deck-link">{t.change}<ArrowUpRight size={14}/></span></button></div>
 <label className="reversal-control"><span>{t.reversals}<small>{t.reversalHint}</small></span><input type="checkbox" checked={reversals} onChange={e=>{setReversals(e.target.checked);reset(spreadId,e.target.checked)}}/><span className="switch" aria-hidden="true"/></label>
 <div className="side-note"><Sparkles size={16} strokeWidth={1}/><p>{t.tip}</p></div></aside>
 <section className="reading-room" aria-label={t.room}><div className="intention-field"><label htmlFor="question">{t.intention}<span>{t.optional}</span></label><div><Sparkles size={17} strokeWidth={1}/><input id="question" value={question} maxLength={240} onChange={e=>setQuestion(e.target.value)} placeholder={t.placeholder}/></div></div>
 <div className="table-header"><div><span className="eyebrow">{spread.short[lang]}</span><h2>{spread.name[lang]}</h2></div><button className="icon-button info-button" onClick={()=>setModal('guide')} aria-label={t.guide}><CircleHelp size={19} strokeWidth={1.25}/></button></div><p className="spread-description">{spread.description[lang]}</p>
 <div className={`table-surround ${spreadId==='celtic'?'celtic':''}`}><div className="celestial-circle" aria-hidden="true"><span/><span/><i>✦</i><b>✧</b></div><div className="table-corner corner-tl"/><div className="table-corner corner-tr"/><div className="table-corner corner-bl"/><div className="table-corner corner-br"/>
 <CardTable key={spread.id} theme={theme} onInspect={(event,index)=>inspection.openMenu(event,previewCard(index))} deck={deck} drawn={drawn} revealed={revealed} positions={spread.positions} lang={lang} onFlip={flip} selected={selected} readingKey={readingKey}/></div>
 <p className="card-zoom-hint">{lang==='en'?'Right-click a card to zoom · Shift + F10 on a focused card':'Clic derecho para ampliar · Mayús + F10 sobre una carta enfocada'}</p><div className="reading-status" aria-live="polite">{count?<><span className="status-dot"/>{all?t.complete:`${count} / ${drawn.length} ${t.revealed}`}</>:<><span className="tiny-star">✧</span>{t.hint}</>}</div>
 <div className="table-actions"><button className="text-button" onClick={()=>reset()} disabled={revealing}><Shuffle size={16}/>{all?t.newReading:t.shuffle}</button><button className="gold-button" onClick={all?()=>reset():revealAll} disabled={revealing}>{all?<RotateCcw size={16}/>:<Sparkles size={16}/>} {all?t.newReading:count?t.revealAll:t.reveal}<ArrowRight size={16}/></button></div>
 </section></div>}
 {deck&&<section className="interpretations"><div className="ornament-divider"><span/>✧<span/></div>{count===0?<div className="empty-reading"><BookOpen size={25} strokeWidth={1}/><h2>{t.emptyTitle}</h2><p>{t.emptyText}</p></div>:<>
 <div className="reading-tabs" aria-label={lang==='en'?'Revealed cards':'Cartas reveladas'}>{spread.positions.map((p,i)=><button key={i} disabled={!revealed[i]} className={selected===i&&revealed[i]?'active':''} onClick={()=>setSelected(i)}><span>{String(i+1).padStart(2,'0')}</span>{p.name[lang]}{revealed[i]&&<Check size={13}/>}</button>)}</div>
 {active&&revealed[selected]&&<article className="card-reading" key={`${drawn[selected]?.id}-${lang}-${deck.id}`}><div className="reading-art"><button aria-label={lang==='en'?'Zoom card':'Ampliar carta'} onClick={e=>inspection.openZoom(previewCard(selected),e.currentTarget)} onContextMenu={e=>inspection.openMenu(e,previewCard(selected))}><img src={cardImage(deck,active.id)} style={{transform:drawn[selected]!.reversed?'rotate(180deg)':undefined}} alt={active.name[lang]}/><span className="zoom-affordance"><ZoomIn size={13}/>{lang==='en'?'Zoom':'Ampliar'}</span></button></div><div className="card-explanation"><span className="eyebrow">{t.selected}</span><h2>{active.name[lang]} <span className="orientation">{drawn[selected]!.reversed?t.reversed:t.upright}</span></h2><span className="theme-word">{active.theme[lang]}</span><p>{drawn[selected]!.reversed?active.reversed[lang]:active.meaning[lang]}</p><div className="position-reading"><span className="eyebrow">{t.inPosition} · {spread.positions[selected]!.name[lang]}</span><p>{spread.positions[selected]!.description[lang]} {lang==='en'?`Consider how ${active.theme.en.toLowerCase()} relates to this part of your story.`:`Considera cómo el tema de ${active.theme.es.toLowerCase()} se relaciona con esta parte de tu historia.`}</p></div><div className="card-advice"><Sparkles size={17}/><p>{active.advice[lang]}</p></div></div></article>}
 {all&&<article className="outcome"><div className="outcome-icon"><Seal/></div><span className="eyebrow">{t.outcomeLabel}</span><h2>{t.outcome}</h2>{question.trim()&&<blockquote><span>{t.context}</span>“{question.trim()}”</blockquote>}<p>{t.outcomeIntro}</p><div className="outcome-threads">{drawn.map((d,i)=>{const c=getCard(d.id,deck);return <p key={i}><span>{spread.positions[i]!.name[lang]}</span><strong>{c.name[lang]}</strong>{d.reversed?` (${t.reversed.toLowerCase()})`:''} — {d.reversed?c.reversed[lang]:c.meaning[lang]}</p>})}</div><div className="synthesis"><span className="eyebrow">{t.potential}</span><p>{drawn.length===1?(lang==='en'?'Carry this theme into your day. ':'Lleva este tema contigo durante el día. '):lang==='en'?`From ${getCard(drawn[0]!.id,deck).theme.en.toLowerCase()} to ${getCard(drawn.at(-1)!.id,deck).theme.en.toLowerCase()}, this spread invites you to connect your starting point with a possible next direction. `:`Desde el tema de ${getCard(drawn[0]!.id,deck).theme.es.toLowerCase()} hasta el de ${getCard(drawn.at(-1)!.id,deck).theme.es.toLowerCase()}, esta tirada te invita a conectar tu punto de partida con una posible dirección. `}{getCard(drawn.at(-1)!.id,deck).advice[lang]}</p></div><small>{t.outcomeClose}</small></article>}
 </>}</section>}
 </main>
 <footer><span className="footer-brand">✧ ARCANA</span><p>{t.footer}</p><span>{t.footnote}</span></footer>
 {modal==='decks'&&<Modal onClose={()=>setModal(null)} label={t.decks}><span className="eyebrow">{t.decks}</span><h2>{t.deckTitle}</h2><p className="modal-intro">{t.deckIntro}</p><div className="deck-grid">{decks.map(d=><button className={`deck-choice ${d.id===deck?.id?'active':''}`} key={d.id} onClick={()=>{setDeckId(d.id);setModal(null)}}><div className="deck-choice-art">{['moon','star','sun'].map(id=><img key={id} src={cardImage(d,id)} alt={getCard(id,d).name[lang]} loading="lazy"/>)}</div><h3>{d.name[lang]}</h3><p>{d.description[lang]}</p><span className="deck-choice-cta">{d.id===deck?.id?t.active:t.select}{d.id===deck?.id?<Check size={16}/>:<ArrowRight size={16}/>}</span></button>)}</div></Modal>}
 {modal==='guide'&&<Modal onClose={()=>setModal(null)} label={t.guide}><Seal/><h2>{t.guideTitle}</h2><p className="modal-intro">{t.guideIntro}</p><div className="guide-steps">{t.guideSteps.map(([n,title,body])=><div key={n}><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></div>)}</div><p className="historical-note">{t.historic}</p><button className="gold-button" onClick={()=>setModal(null)}>{t.return}<ArrowRight size={16}/></button></Modal>}
 {inspection.overlay}
 </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
