import {newProject,id,revision,frame,annotations,addRevision,undo,redo,addFrame,selectFrame,selectRevision,changeFrameRevision,deleteFrame,moveFrame,type Project,type Profile,type Tool,type Point} from './project';
import {CanvasEngine,blobFromCanvas,isTyping} from './canvas';
import {saveProject,loadLast,listProjects,loadProject,storeAsset,getBlob} from './storage';
import {GenerationQueue,generateRevision,api} from './generation';
import {exportProject,importProject,download,safeName,sequence,gif,webm,contactSheet} from './export';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const input=(s:string)=>$<HTMLInputElement>(s);
const button=(s:string,fn:()=>void|Promise<void>)=>$(s).addEventListener('click',()=>{Promise.resolve().then(fn).catch(fail);});
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let project=newProject(),profile:Profile='FAST',busy=false,saveTimer:ReturnType<typeof setTimeout>,toastTimer:ReturnType<typeof setTimeout>,playing=false,playTime=0,playDirection=1,renderVersion=0,maxBatch=24;
let saveChain=Promise.resolve();const queue=new GenerationQueue(),thumbs=new Map<string,string>();
const engine=new CanvasEngine($<HTMLCanvasElement>('#Flip-slop-canvas'),()=>project,()=>{changed();},openComment);
function toast(message:string){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
function fail(e:unknown){toast(e instanceof Error?e.message:'Something went wrong.');}
function changed(immediate=false){$('#save-state').textContent='● Saving…';clearTimeout(saveTimer);if(immediate)void persist();else saveTimer=setTimeout(()=>void persist(),650);void engine.render();}
async function persist(){const snapshot=structuredClone(project);saveChain=saveChain.catch(()=>{}).then(()=>saveProject(snapshot));try{await saveChain;$('#save-state').textContent='● Saved locally';}catch{ $('#save-state').textContent='● Save failed';toast('Local storage is full or unavailable. Export your project to keep it safe.');}}
function showDialog(html:string){$('#dialog-content').innerHTML=html;$<HTMLDialogElement>('#dialog').showModal();}
function closeDialog(){$<HTMLDialogElement>('#dialog').close();}
async function confirmAction(title:string,message:string,label:string):Promise<boolean>{showDialog(`<h2>${esc(title)}</h2><p>${esc(message)}</p><div class="modal-actions"><button id="decline">Cancel</button><button id="accept" class="dark">${esc(label)}</button></div>`);return new Promise(resolve=>{let done=false;const finish=(answer:boolean)=>{if(done)return;done=true;closeDialog();resolve(answer);};button('#accept',()=>finish(true));button('#decline',()=>finish(false));$('#dialog').addEventListener('close',()=>finish(false),{once:true});});}
function openComment(point:Point){if(busy)return;showDialog('<h2>A note, right here.</h2><p>Tell the model what to change or preserve at this point.</p><textarea id="comment-text" aria-label="Canvas comment" maxlength="1000" placeholder="Keep this face exactly the same…"></textarea><button id="save-comment" class="dark">Add note</button>');button('#save-comment',()=>{const text=$<HTMLTextAreaElement>('#comment-text').value.trim();if(!text)return;annotations(project).push({id:id(),kind:'comment',points:[point],radius:.01,color:'#d1e888',text});changed();closeDialog();});$<HTMLTextAreaElement>('#comment-text').focus();}
const icons:Record<Tool,string>={select:'<path d="M5 3l13 8-7 2-3 7z"/>',lasso:'<path d="M6 17c-7-4-3-13 6-13 10 0 12 12 2 13-6 1-8-1-7-4 2-3 6 2 3 6l-2 2"/>',brush:'<path d="M8 14L18 3l3 3-11 10M8 14c-5-1-3 5-6 6 5 2 9 0 8-4"/>',mask:'<path d="M4 4h16v16H4zM4 10l6-6M4 16L16 4M6 20L20 6M12 20l8-8M18 20l2-2"/>',eraser:'<path d="M3 14L14 3l7 7-11 11H8zM9 8l7 7M10 21h12"/>',sketch:'<path d="M3 17L17 3l4 4L7 21H3zM14 6l4 4M3 17l4 4"/>',arrow:'<path d="M4 20L20 4M9 4h11v11"/>',comment:'<path d="M4 4h16v12H9l-5 5zM8 8h8M8 12h5"/>',crop:'<path d="M6 2v16h16M2 6h16v16"/>',hand:'<path d="M7 12V6a2 2 0 014 0v5-7a2 2 0 014 0v7-5a2 2 0 014 0v6-3a2 2 0 014 0v6c0 6-5 8-10 5l-7-6a2 2 0 013-3l3 2"/>',zoom:'<circle cx="10" cy="10" r="6"/><path d="M15 15l6 6M7 10h6M10 7v6"/>'};
const shortcuts:Partial<Record<Tool,string>>={select:'V',brush:'B',mask:'M',arrow:'A',comment:'C',hand:'H',eraser:'E',lasso:'L',sketch:'S',crop:'X',zoom:'Z'};
$('#tools').innerHTML=Object.entries(icons).map(([tool,svg])=>`<button class="tool ${tool==='select'?'selected':''}" data-tool="${tool}" aria-label="${tool[0]!.toUpperCase()+tool.slice(1)} tool" title="${tool[0]!.toUpperCase()+tool.slice(1)} (${shortcuts[tool as Tool]})"><svg viewBox="0 0 24 24">${svg}</svg></button>`).join('');
function setTool(tool:Tool){engine.tool=tool;document.querySelectorAll<HTMLElement>('[data-tool]').forEach(el=>{el.classList.toggle('selected',el.dataset.tool===tool);el.setAttribute('aria-pressed',String(el.dataset.tool===tool));});$('#tool-hint').textContent=({select:'Drag to select an area. Scroll to zoom.',lasso:'Draw around the area you want to change.',brush:'Paint directly on the canvas. Save a drawing revision to commit.',mask:'Paint the area you want the AI to edit.',eraser:'Drag over annotations to erase them.',sketch:'Sketch an idea to guide the next generation.',arrow:'Draw a path from an object toward its destination.',comment:'Click a point to leave an editing note.',crop:'Drag a crop rectangle, then choose Apply crop.',hand:'Drag to move the canvas. Scroll to zoom.',zoom:'Click to zoom in. Alt-click to zoom out.'})[tool];engine.canvas.style.cursor=tool==='hand'?'grab':tool==='comment'?'cell':'crosshair';}
$('#tools').addEventListener('click',e=>{const tool=(e.target as HTMLElement).closest<HTMLElement>('[data-tool]')?.dataset.tool as Tool;if(tool)setTool(tool);});
input('#brush-color').oninput=()=>engine.color=input('#brush-color').value;
input('#brush-size').oninput=()=>engine.radius=Number(input('#brush-size').value)/1000;
button('#clear-guides',()=>{project.annotations[project.activeRevisionId??'draft']=[];changed();});
button('#fit',()=>engine.fit());button('#zoom-in',()=>{engine.camera.zoom(1.2,{x:engine.canvas.clientWidth/2,y:engine.canvas.clientHeight/2});void engine.render();});button('#zoom-out',()=>{engine.camera.zoom(1/1.2,{x:engine.canvas.clientWidth/2,y:engine.canvas.clientHeight/2});void engine.render();});
async function thumbnail(assetId:string){if(thumbs.has(assetId))return thumbs.get(assetId)!;const b=await createImageBitmap(await getBlob(assetId),{resizeWidth:220});const c=document.createElement('canvas');c.width=b.width;c.height=b.height;c.getContext('2d')!.drawImage(b,0,0);b.close();const url=URL.createObjectURL(await blobFromCanvas(c,'image/webp'));thumbs.set(assetId,url);return url;}
async function renderTimeline(){const version=++renderVersion;const animation=project.mode==='ANIMATE';const items=animation?project.frames.map((f,i)=>({id:f.id,r:revision(project,f.revisionId)!,label:String(i+1).padStart(2,'0'),active:f.id===project.activeFrameId,key:f.keyframe,status:f.status})):project.revisions.map((r,i)=>({id:r.id,r,label:String(i+1).padStart(2,'0'),active:r.id===project.activeRevisionId,key:false,status:'READY'}));
  if(!items.length){$('#timeline-items').innerHTML='<div class="empty-history"><span>↶</span><div>Every little change, kept.<small>Your images and revisions will find a home here.</small></div></div>';return;}
  const html=await Promise.all(items.map(async item=>{const url=await thumbnail(item.r.imageAssetId);const parent=project.revisions.findIndex(r=>r.id===item.r.parentId);return `<button class="thumb ${item.active?'active':''} ${item.status==='STALE'?'stale':''}" data-item="${item.id}" draggable="${animation}" title="${esc(item.r.prompt)}${item.status==='READY'?'':' · '+item.status}"><img src="${url}" alt="${esc(item.r.prompt.slice(0,100)||project.description||'Project image')}">${!animation&&parent>=0?`<span class="branch">↳ ${String(parent+1).padStart(2,'0')}</span>`:''}<span class="thumb-label"><strong>${item.key?'◆ ':''}${item.label}</strong><small>${animation?(item.status==='READY'?(item.r.generation?'AI':'MANUAL'):item.status):esc(item.r.prompt||'Uploaded image')}</small></span></button>`;}));if(version===renderVersion)$('#timeline-items').innerHTML=html.join('');
}
function render(){const anim=project.mode==='ANIMATE',edit=project.mode!=='CREATE',has=!!revision(project);input('#project-name').value=project.name;document.querySelectorAll<HTMLElement>('[data-mode]').forEach(el=>el.classList.toggle('active',el.dataset.mode===project.mode));const titles={CREATE:'Make something<br><em>unexpected.</em>',EDIT:'A little change.<br><em>A new possibility.</em>',ANIMATE:'One frame.<br><em>Then a little more.</em>'};$('#mode-title').innerHTML=titles[project.mode];$('#mode-eyebrow').textContent={CREATE:'01 / THE START OF SOMETHING',EDIT:'02 / FOLLOW YOUR CURIOSITY',ANIMATE:'03 / FIND YOUR RHYTHM'}[project.mode];$('#mode-description').textContent={CREATE:'A sentence, a sketch, a spark. Start here.',EDIT:'Give your idea a nudge in a new direction.',ANIMATE:'Small changes. A world coming to life.'}[project.mode];$('#prompt-label').innerHTML=edit?'YOUR DIRECTION <span>↗</span>':'YOUR IDEA <span>✧</span>';$('#edit-options').hidden=!edit;$('#animate-options').hidden=!anim;$('#playback-controls').hidden=!anim;$('#frame-controls').hidden=!anim;$('#history-label').hidden=anim;$('#generate').innerHTML=busy?'Working…':`${anim?'Generate motion':edit?'Generate edit':'Generate image'} <span>↗</span>`;input('#size').disabled=has;$('#dimensions').textContent=`${project.size.width} × ${project.size.height} PX`;$('#canvas-title').textContent=has?project.name.toUpperCase():'YOUR NEXT LITTLE MASTERPIECE';$('#canvas-tag').textContent=has?`${anim?'FRAME':'REVISION'} ${String(anim?project.frames.findIndex(f=>f.id===project.activeFrameId)+1:project.revisions.findIndex(r=>r.id===project.activeRevisionId)+1).padStart(2,'0')} / ${frame(project)?.keyframe&&anim?'KEYFRAME':'THE WORK IN PROGRESS'}`:'01 / A BLANK CANVAS';input('#fps').value=String(project.fps);input('#loop').value=project.loop;input('#duration').value=String(frame(project)?.durationMs??0);$('#keyframe').textContent=frame(project)?.keyframe?'◆ Keyframe':'◇ Keyframe';$<HTMLTextAreaElement>('#scene-bible').value=project.sceneBible;$<HTMLTextAreaElement>('#description').value=project.description;
  $('#constraints').innerHTML=['character identity','camera','background','lighting','palette','typography'].map(c=>`<button class="chip ${project.constraints.includes(c)?'on':''}" data-constraint="${c}" aria-pressed="${project.constraints.includes(c)}">${project.constraints.includes(c)?'✓':'+'} ${c}</button>`).join('');
  for(const selector of ['#frame-history','#generate','#between','#repair','#regenerate','#import-image','#add-frame','#duplicate','#delete-frame','#move-left','#move-right','#keyframe','#commit-drawing','#apply-crop','#projects','#canonical','#clear-guides'])$<HTMLButtonElement>(selector).disabled=busy;
  $<HTMLButtonElement>('#undo').disabled=busy||!revision(project)?.parentId;$<HTMLButtonElement>('#redo').disabled=busy||!project.redo[project.activeRevisionId??''];engine.canvas.style.pointerEvents=busy?'none':'auto';void renderTimeline();void engine.render();
}
async function setMode(mode:Project['mode']){if(busy)return;stopPlayback();project.mode=mode;if(mode==='ANIMATE'&&!project.frames.length&&project.activeRevisionId)addFrame(project);if(mode==='ANIMATE'&&project.frames.length)selectFrame(project,project.activeFrameId??project.frames[0]!.id);changed();render();}
document.querySelectorAll<HTMLElement>('[data-mode]').forEach(el=>el.onclick=()=>void setMode(el.dataset.mode as Project['mode']));
document.querySelectorAll<HTMLElement>('[data-profile]').forEach(el=>el.onclick=()=>{profile=el.dataset.profile as Profile;document.querySelectorAll<HTMLElement>('[data-profile]').forEach(b=>{b.classList.toggle('selected',b===el);b.setAttribute('aria-pressed',String(b===el));});});
$('#constraints').onclick=e=>{const c=(e.target as HTMLElement).closest<HTMLElement>('[data-constraint]')?.dataset.constraint;if(c){project.constraints=project.constraints.includes(c)?project.constraints.filter(x=>x!==c):[...project.constraints,c];changed();render();}};
$<HTMLTextAreaElement>('#prompt').oninput=()=>{project.draftPrompt=$<HTMLTextAreaElement>('#prompt').value;changed();};
input('#project-name').oninput=()=>{project.name=input('#project-name').value||'Untitled study';changed();};
$<HTMLTextAreaElement>('#scene-bible').oninput=()=>{project.sceneBible=$<HTMLTextAreaElement>('#scene-bible').value.slice(0,4000);changed();};$<HTMLTextAreaElement>('#description').oninput=()=>{project.description=$<HTMLTextAreaElement>('#description').value.slice(0,4000);changed();};
function changeSize(){if(revision(project))return;const value=input('#size').value;$('#custom-size').hidden=value!=='custom';const [width,height]=value==='custom'?[Number(input('#custom-width').value),Number(input('#custom-height').value)]:value.split('x').map(Number);if(!width||!height||width<256||height<256||width%16||height%16||width/height>3||height/width>3||width*height>8294400)return;project.size={width,height};engine.fit();changed();render();}
input('#size').onchange=changeSize;input('#custom-width').onchange=changeSize;input('#custom-height').onchange=changeSize;
button('#example',()=>{$<HTMLTextAreaElement>('#prompt').value=project.mode==='CREATE'?'A tiny handmade clay robot sitting at a wooden desk in a small workshop, warm morning sunlight, tactile stop-motion aesthetic.':project.mode==='EDIT'?'Add a small red ceramic coffee mug on the desk. Preserve everything else.':'Lift the red mug slowly toward the robot’s mouth. Keep the camera still.';project.draftPrompt=$<HTMLTextAreaElement>('#prompt').value;changed();});
button('#import-image',()=>input('#image-input').click());
async function uploadImage(file:File){stopPlayback();const asset=await storeAsset(file,'UPLOADED_IMAGE');if(!project.revisions.length){const scale=Math.min(1,2048/Math.max(asset.width,asset.height));project.size={width:Math.max(256,Math.round(asset.width*scale/16)*16),height:Math.max(256,Math.round(asset.height*scale/16)*16)};}
  const f=project.mode==='ANIMATE'?frame(project):undefined;const r=addRevision(project,asset,file.name,project.activeRevisionId);if(f)changeFrameRevision(project,f.id,r.id);await persist();engine.fit();render();}
input('#image-input').onchange=()=>{const file=input('#image-input').files?.[0];if(file)void uploadImage(file).catch(fail);input('#image-input').value='';};
engine.canvas.addEventListener('dragover',e=>e.preventDefault());engine.canvas.addEventListener('drop',e=>{e.preventDefault();if(!busy&&e.dataTransfer?.files[0])void uploadImage(e.dataTransfer.files[0]).catch(fail);});
button('#add-reference',()=>input('#reference-input').click());
async function renderReferences(){const html=await Promise.all(project.references.map(async id=>{const url=await thumbnail(id);return `<div class="ref"><img src="${url}" alt="Visual reference"><button data-remove-ref="${id}" aria-label="Remove reference">×</button></div>`;}));$('#references').innerHTML=html.join('')||'<span class="muted">Keep a character, a color, a feeling.</span>';}
input('#reference-input').onchange=()=>{void (async()=>{for(const file of Array.from(input('#reference-input').files??[])){if(project.references.length>=3){toast('Use up to three additional references.');break;}const a=await storeAsset(file,'REFERENCE');project.assets[a.id]=a;project.references.push(a.id);}changed();await renderReferences();input('#reference-input').value='';})().catch(fail);};
$('#references').onclick=e=>{const a=(e.target as HTMLElement).dataset.removeRef;if(a){project.references=project.references.filter(x=>x!==a);changed();void renderReferences();}};
function navigateRevision(direction:'undo'|'redo'){if(busy)return;const f=project.mode!=='CREATE'&&frame(project)?.revisionId===project.activeRevisionId?frame(project):undefined;(direction==='undo'?undo:redo)(project);if(f&&project.activeRevisionId)changeFrameRevision(project,f.id,project.activeRevisionId);changed();render();}
button('#undo',()=>navigateRevision('undo'));button('#redo',()=>navigateRevision('redo'));
$('#timeline-items').onclick=e=>{if(busy)return;const el=(e.target as HTMLElement).closest<HTMLElement>('[data-item]');if(!el)return;stopPlayback();if(project.mode==='ANIMATE')selectFrame(project,el.dataset.item!);else selectRevision(project,el.dataset.item!);changed();render();};
let dragged:string|undefined;$('#timeline-items').addEventListener('dragstart',e=>{if(busy){e.preventDefault();return;}dragged=(e.target as HTMLElement).closest<HTMLElement>('[data-item]')?.dataset.item;});$('#timeline-items').addEventListener('dragover',e=>e.preventDefault());$('#timeline-items').addEventListener('drop',e=>{e.preventDefault();const to=(e.target as HTMLElement).closest<HTMLElement>('[data-item]')?.dataset.item;if(!busy&&dragged&&to&&project.mode==='ANIMATE'){moveFrame(project,dragged,project.frames.findIndex(f=>f.id===to));changed();render();}});
button('#frame-history',()=>{const f=frame(project);if(!f)return;showDialog(`<h2>Every version, kept.</h2><p>Choose a revision for this frame. Dependent frames will be marked stale.</p><div>${project.revisions.map((r,i)=>`<button class="project-row" data-frame-revision="${r.id}">${String(i+1).padStart(2,'0')} · ${esc(r.prompt||'Uploaded image')}<small>${r.id===f.revisionId?'Current frame version':r.parentId?'Revision branch':'Original image'}</small></button>`).join('')}</div>`);document.querySelectorAll<HTMLElement>('[data-frame-revision]').forEach(el=>el.onclick=()=>{changeFrameRevision(project,f.id,el.dataset.frameRevision!);changed();render();closeDialog();});});
button('#add-frame',()=>{addFrame(project,project.activeRevisionId,Math.max(0,project.frames.findIndex(f=>f.id===project.activeFrameId)+1));changed();render();});button('#duplicate',()=>{const f=frame(project);if(f){const copy=addFrame(project,f.revisionId,project.frames.indexOf(f)+1);copy.durationMs=f.durationMs;changed();render();}});button('#delete-frame',()=>{if(project.activeFrameId){deleteFrame(project,project.activeFrameId);changed();render();}});button('#keyframe',()=>{const f=frame(project);if(f){f.keyframe=!f.keyframe;changed();render();}});for(const [selector,offset] of [['#move-left',-1],['#move-right',1]] as const)button(selector,()=>{if(project.activeFrameId){moveFrame(project,project.activeFrameId,project.frames.findIndex(f=>f.id===project.activeFrameId)+offset);changed();render();}});
input('#fps').onchange=()=>{project.fps=Math.max(1,Math.min(60,Number(input('#fps').value)||8));changed();};input('#loop').onchange=()=>{project.loop=input('#loop').value as Project['loop'];changed();};input('#duration').onchange=()=>{const f=frame(project);if(f){f.durationMs=Math.max(0,Math.min(10000,Number(input('#duration').value)))||undefined;changed();}};
input('#onion').onchange=()=>{engine.onion=input('#onion').value;void engine.render();};input('#onion-opacity').oninput=()=>{engine.opacity=Number(input('#onion-opacity').value)/100;$('#onion-value').textContent=`${input('#onion-opacity').value}%`;void engine.render();};
function stepFrame(offset:number){if(!project.frames.length)return;const index=project.frames.findIndex(f=>f.id===project.activeFrameId);selectFrame(project,project.frames[(index+offset+project.frames.length)%project.frames.length]!.id);render();}
button('#previous',()=>{stopPlayback();stepFrame(-1);});button('#next',()=>{stopPlayback();stepFrame(1);});
function stopPlayback(){playing=false;engine.showGuidance=true;$('#play').textContent='▶ Play';}
function playback(time:number){if(!playing)return;const duration=frame(project)?.durationMs??1000/project.fps;if(time-playTime>=duration){playTime+=duration;let index=project.frames.findIndex(f=>f.id===project.activeFrameId)+playDirection;if(index>=project.frames.length||index<0){if(project.loop==='once'){stopPlayback();return;}if(project.loop==='pingpong'){playDirection*=-1;index=Math.max(0,Math.min(project.frames.length-1,index+playDirection*2));}else index=0;}selectFrame(project,project.frames[index]!.id);void engine.render();document.querySelectorAll<HTMLElement>('[data-item]').forEach(el=>el.classList.toggle('active',el.dataset.item===project.activeFrameId));}requestAnimationFrame(playback);}
function togglePlay(){if(busy||!project.frames.length)return;if(playing){stopPlayback();render();return;}playing=true;engine.showGuidance=false;playTime=performance.now();playDirection=1;$('#play').textContent='Ⅱ Pause';requestAnimationFrame(playback);}
button('#play',togglePlay);
function setBusy(value:boolean,message='Making a little magic…'){busy=value;$('#busy-overlay').hidden=!value;$('#busy-text').textContent=message;render();}
button('#cancel',()=>{queue.cancel();$('#busy-text').textContent='Stopping…';});
async function guidance(){const list=annotations(project);const hasMarks=list.some(a=>['sketch','brush','arrow','comment'].includes(a.kind));const hasMask=list.some(a=>['mask','select','lasso'].includes(a.kind));return {guidance:hasMarks?await blobFromCanvas(await engine.composite(project.activeRevisionId,'guidance')):undefined,mask:hasMask&&revision(project)?await blobFromCanvas(await engine.composite(project.activeRevisionId,'mask')):undefined};}
async function generateSingle(repair=false){const prompt=$<HTMLTextAreaElement>('#prompt').value.trim();if(!prompt){toast('Give your image a little direction first.');$('#prompt').focus();return;}const sourceId=project.mode==='CREATE'?undefined:project.activeRevisionId;if(project.mode!=='CREATE'&&!sourceId){toast('Create or upload an image first.');return;}stopPlayback();setBusy(true,repair?'Restoring the details…':'Making a little magic…');const activeProject=project;try{const guides=await guidance();await queue.enqueue(signal=>generateRevision(activeProject,{prompt,profile:repair?'PRECISE':profile,quality:input('#quality').value,sourceId,repair,...guides,signal,frameId:project.mode!=='CREATE'&&frame(project)?.revisionId===sourceId?project.activeFrameId:undefined,previousId:repair?project.frames[project.frames.findIndex(f=>f.id===project.activeFrameId)-1]?.revisionId:undefined}));await persist();toast('A new revision. The original is safely kept.');}catch(e){if(queue.controller?.signal.aborted||(e instanceof DOMException&&e.name==='AbortError'))toast('Stopped. Completed work is saved.');else throw e;}finally{setBusy(false);}}
button('#generate',()=>project.mode==='ANIMATE'?generateBatch('motion'):generateSingle());button('#repair',()=>generateSingle(true));button('#between',()=>generateBatch('between'));button('#regenerate',()=>generateBatch('forward'));
async function generateBatch(kind:'motion'|'between'|'forward'){
  const start=frame(project),prompt=$<HTMLTextAreaElement>('#prompt').value.trim();if(!start){toast('Add an image to the timeline first.');return;}if(!prompt){toast('Describe the motion first.');$('#prompt').focus();return;}
  const startIndex=project.frames.indexOf(start);const target=kind==='between'?project.frames.slice(startIndex+1).find(f=>f.keyframe):undefined;if(kind==='between'&&(!start.keyframe||!target)){toast('Select a start keyframe with another keyframe after it.');return;}
  let existing=kind==='forward'?project.frames.slice(startIndex+1):kind==='between'?project.frames.slice(startIndex+1,project.frames.indexOf(target!)):[];
  if(kind==='forward'){const keyIndex=existing.findIndex(f=>f.keyframe);if(keyIndex>=0)existing=existing.slice(0,keyIndex);if(!existing.length){toast('No following non-keyframes to regenerate.');return;}}
  const count=existing.length||Number(input('#frame-count').value);if(!Number.isInteger(count)||count<1||count>maxBatch){toast(`Choose 1–${maxBatch} frames per batch.`);return;}
  if(!(await confirmAction(kind==='between'?'Fill the space between.':'A little motion, frame by frame.',`Generate ${count} new images with ${profile==='FAST'?'Flare':'Sunburst'}? Each frame is a separate API request. Completed frames are saved as we go.`, `Generate ${count} frames`)))return;
  stopPlayback();setBusy(true,`Planning ${count} frames…`);const p=project,initialGuides={...await guidance(),annotationSnapshot:structuredClone(annotations(project))};let previous=start;let runningFrame:typeof start|undefined;
  try{await queue.enqueue(async signal=>{
    const plan=await api('/api/motion/plan',{count,prompt},signal);for(let i=0;i<count;i++){
      if(signal.aborted)throw new DOMException('Cancelled','AbortError');$('#busy-text').textContent=`Generating frame ${i+1} / ${count}`;
      const destination=existing[i];runningFrame=destination;if(destination){destination.status='GENERATING';void renderTimeline();}
      const instruction=kind==='between'?plan.frames[i].instruction:`${prompt}\nThis is incremental motion step ${i+1} of ${count}. Advance the motion to ${Math.round((i+1)/count*100)}% of the full intended movement, using the previous image as the current state. Preserve scene and identity.`;
      const r=await generateRevision(p,{prompt:instruction,profile,quality:input('#quality').value,sourceId:previous.revisionId,targetId:target?.revisionId,...initialGuides,signal,activate:false});
      if(signal.aborted)throw new DOMException('Cancelled','AbortError');const next=destination??addFrame(p,r.id,p.frames.indexOf(previous)+1);if(destination)changeFrameRevision(p,next.id,r.id);next.generatedFromFrameId=previous.id;next.generatedFromRevisionId=previous.revisionId;next.motionInstruction=instruction;next.status='READY';next.keyframe=false;selectFrame(p,next.id);previous=next;runningFrame=undefined;await persist();render();
    }
  });toast(`${count} frames generated. Press Play to see your idea move.`);}catch(e){if(runningFrame){runningFrame.status='FAILED';await persist();}if(e instanceof DOMException&&e.name==='AbortError')toast('Stopped. Your completed frames are saved.');else throw e;}finally{setBusy(false);}
}
button('#canonical',()=>{if(project.activeRevisionId){project.canonicalRevisionId=project.activeRevisionId;changed();toast('This image now anchors visual consistency.');}});
button('#commit-drawing',async()=>{const blob=await blobFromCanvas(await engine.composite());const a=await storeAsset(blob,'UPLOADED_IMAGE'),f=project.mode==='ANIMATE'?frame(project):undefined,r=addRevision(project,a,'Manual drawing',project.activeRevisionId);if(f)changeFrameRevision(project,f.id,r.id);await persist();render();});
button('#apply-crop',async()=>{const crop=annotations(project).find(a=>a.kind==='crop');if(!crop||crop.points.length<2){toast('Draw a crop rectangle first.');return;}if(project.frames.length){toast('Crop before adding animation frames so frame dimensions remain stable.');return;}const a=crop.points[0]!,b=crop.points.at(-1)!,x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y);if(w<.05||h<.05){toast('Choose a larger crop.');return;}const source=await engine.composite();const c=document.createElement('canvas');c.width=project.size.width;c.height=project.size.height;c.getContext('2d')!.drawImage(source,x*source.width,y*source.height,w*source.width,h*source.height,0,0,c.width,c.height);const asset=await storeAsset(await blobFromCanvas(c),'UPLOADED_IMAGE');addRevision(project,asset,'Cropped composition',project.activeRevisionId);await persist();render();});
button('#projects',async()=>{await persist();const projects=await listProjects();showDialog(`<h2>Your little worlds.</h2><p>Projects live in this browser. Export a project to take it with you.</p><div class="inline-actions"><button id="new-project">+ New project</button><button id="open-project-file">Import .Flip-slop</button></div><div>${projects.map(p=>`<button class="project-row" data-open-project="${p.id}">${esc(p.name)}<small>${p.frames.length} frames · ${p.revisions.length} revisions · ${new Date(p.updatedAt).toLocaleDateString()}</small></button>`).join('')}</div>`);button('#new-project',async()=>{await switchProject(newProject());closeDialog();});button('#open-project-file',()=>input('#project-input').click());document.querySelectorAll<HTMLElement>('[data-open-project]').forEach(el=>el.onclick=()=>{void loadProject(el.dataset.openProject!).then(async p=>{if(p){await switchProject(p);closeDialog();}}).catch(fail);});});
async function switchProject(p:Project){queue.cancel();stopPlayback();clearTimeout(saveTimer);await persist();project=p;$<HTMLTextAreaElement>('#prompt').value=p.draftPrompt;engine.cache.clear();for(const url of thumbs.values())URL.revokeObjectURL(url);thumbs.clear();input('#size').value=`${p.size.width}x${p.size.height}`;engine.fit();await renderReferences();await persist();render();}
input('#project-input').onchange=()=>{const file=input('#project-input').files?.[0];if(file)void importProject(file).then(switchProject).then(()=>{closeDialog();toast('Project opened. Every revision, ready to revisit.');}).catch(fail);input('#project-input').value='';};
button('#export',()=>{showDialog(`<h2>Out into the world.</h2><p>Keep an editable project, or share what you’ve made.</p><div class="export-grid"><button data-export="project">.Flip-slop project<small>All assets, frames & revisions</small></button><button data-export="original">Original image<small>Untouched generated binary</small></button><button data-export="png">PNG image<small>Source resolution + drawing</small></button><button data-export="jpeg">JPEG image<small>Flattened, high quality</small></button><button data-export="webp">WebP image<small>Flattened, compact</small></button><button data-export="sequence">PNG sequence<small>Every frame in a ZIP</small></button><button data-export="webm">WebM animation<small>A playable stop-motion film</small></button><button data-export="gif">Animated GIF<small>Source resolution, easy to share</small></button><button data-export="contact">Contact sheet<small>The whole story at a glance</small></button></div><p>Re-encoded exports may lose embedded image metadata. Original assets and generation records stay in the project.</p><p id="export-progress" role="status"></p>`);document.querySelectorAll<HTMLButtonElement>('[data-export]').forEach(b=>b.onclick=()=>{void doExport(b.dataset.export!).catch(fail);});});
async function doExport(kind:string){if(busy){toast('Stop generation before exporting.');return;}const status=(message:string)=>{$('#export-progress').textContent=message;};const buttons=document.querySelectorAll<HTMLButtonElement>('[data-export]');buttons.forEach(b=>b.disabled=true);stopPlayback();const exportState=structuredClone(project);const name=safeName(exportState.name);try{let blob:Blob,ext:string;if(kind==='project'){await persist();blob=await exportProject(exportState);ext='Flip-slop';}else if(['sequence','gif','webm','contact'].includes(kind)){if(!exportState.frames.length)throw Error('Add animation frames first.');status('Preparing frames…');blob=kind==='sequence'?await sequence(exportState,engine,status):kind==='gif'?await gif(exportState,engine,status):kind==='webm'?await webm(exportState,engine,status):await contactSheet(exportState,engine);ext={sequence:'zip',gif:'gif',webm:'webm',contact:'png'}[kind]!;}else if(kind==='original'){const r=revision(exportState);if(!r)throw Error('Create or upload an image first.');blob=await getBlob(r.imageAssetId);ext=blob.type.split('/')[1]!;}else{blob=await blobFromCanvas(await engine.composite(exportState.activeRevisionId,'flatten',exportState),`image/${kind}`);ext=kind;}download(blob,`${name}${kind==='contact'?'-contact-sheet':''}.${ext}`);status('Export ready.');}finally{buttons.forEach(b=>b.disabled=false);}}
button('#help',()=>showDialog('<h2>A few handy shortcuts.</h2><p>V Select · L Lasso · B Brush · M Mask · E Eraser<br>S Sketch · A Motion arrow · C Comment · X Crop<br>H Hand · Z Zoom · + / − Zoom in or out</p><p>Hold Space to pan. In the timeline, Space plays or pauses.<br>← / → Step through frames.<br>⌘ / Ctrl Z Undo · ⌘ / Ctrl Shift Z Redo.</p><p>Every AI edit keeps the source image. Timeline frames point to revisions, so a repaired frame never erases its history.</p>'));
window.addEventListener('keydown',e=>{if(isTyping(e.target)||$<HTMLDialogElement>('#dialog').open)return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();navigateRevision(e.shiftKey?'redo':'undo');return;}if(e.code==='Space'&&(e.target as HTMLElement).closest('.timeline')){e.preventDefault();togglePlay();return;}if(busy)return;if(e.key==='ArrowLeft'){e.preventDefault();stepFrame(-1);}else if(e.key==='ArrowRight'){e.preventDefault();stepFrame(1);}else if(e.key==='+'||e.key==='=')$('#zoom-in').click();else if(e.key==='-')$('#zoom-out').click();else{const tool=(Object.entries(shortcuts).find(([,key])=>key.toLowerCase()===e.key.toLowerCase())?.[0]) as Tool|undefined;if(tool)setTool(tool);}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPlayback();void persist();}});
async function initialize(){try{const p=await loadLast();if(p)project=p;}catch{toast('Could not restore local storage. You can import a saved project.');}$<HTMLTextAreaElement>('#prompt').value=project.draftPrompt;render();engine.fit();await renderReferences();try{const [health,models]=await Promise.all([fetch('/api/health').then(r=>r.json()),fetch('/api/models').then(r=>r.json())]);maxBatch=models.maxBatch;input('#frame-count').max=String(maxBatch);$('#connection-label').textContent=health.configured?'OpenAI connected':'Configure server .env';if(!health.configured)$('#connection').style.background='#be925a';}catch{$('#connection-label').textContent='Offline · local tools ready';$('#connection').style.background='#be925a';}await persist();}
void initialize();
