import {zip,unzip,strToU8,strFromU8,type Zippable} from 'fflate';
import {getBlob,putBlob} from './storage';
import {migrateProject,revision,assetReferences,type Project} from './project';
import {blobFromCanvas,type CanvasEngine} from './canvas';
export function download(blob:Blob,name:string){const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export const safeName=(name:string)=>name.replace(/[^a-zA-Z0-9_-]+/g,'-').slice(0,80)||'flip-slop';
export const zipFiles=(files:Zippable)=>new Promise<Uint8Array>((resolve,reject)=>zip(files,{level:0},(e,data)=>e?reject(e):resolve(data)));
export async function exportProject(p:Project){const files:Zippable={'project.json':strToU8(JSON.stringify(p)),'manifest.json':strToU8(JSON.stringify({format:'Flip-slop',version:1}))};for(const a of Object.keys(assetReferences(p)))files[`assets/${a}`]=new Uint8Array(await (await getBlob(a)).arrayBuffer());return new Blob([await zipFiles(files) as BlobPart],{type:'application/zip'});}
export async function importProject(blob:Blob){if(blob.size>512_000_000)throw Error('Project archive exceeds 512 MB.');let total=0;  const bytes=new Uint8Array(await blob.arrayBuffer());const data=await new Promise<Record<string,Uint8Array>>((resolve,reject)=>unzip(bytes,{filter:f=>{total+=f.originalSize;if(total>768_000_000)throw Error('Expanded project exceeds 768 MB.');return f.name==='project.json'||/^assets\/[\w-]+$/.test(f.name);}},(e,result)=>e?reject(e):resolve(result)));
  if(!data['project.json']||data['project.json'].length>20_000_000)throw Error('Missing or oversized project metadata.');const p=migrateProject(JSON.parse(strFromU8(data['project.json'])));
  for(const a of Object.keys(assetReferences(p))){if(!data[`assets/${a}`])throw Error('Project archive is missing an image.');const meta=p.assets[a]!;if(!['image/png','image/jpeg','image/webp'].includes(meta.mimeType))throw Error('Unsupported asset format.');const b=new Blob([data[`assets/${a}`]! as BlobPart],{type:meta.mimeType});const bitmap=await createImageBitmap(b);if(bitmap.width>8192||bitmap.height>8192){bitmap.close();throw Error('Oversized image.');}bitmap.close();}
  for(const a of Object.keys(assetReferences(p)))await putBlob(a,new Blob([data[`assets/${a}`]! as BlobPart],{type:p.assets[a]!.mimeType}));return p;
}
export async function sequence(p:Project,engine:CanvasEngine,progress:(s:string)=>void){const files:Zippable={};for(let i=0;i<p.frames.length;i++){progress(`Exporting frame ${i+1} / ${p.frames.length}`);const c=await engine.composite(p.frames[i]!.revisionId,'flatten',p);files[`flip-slop-${String(i+1).padStart(4,'0')}.png`]=new Uint8Array(await (await blobFromCanvas(c)).arrayBuffer());}return new Blob([await zipFiles(files) as BlobPart],{type:'application/zip'});}
export async function gif(p:Project,engine:CanvasEngine,progress:(s:string)=>void){
  const worker=new Worker('/gif-worker.js',{type:'module'});
  const exchange=(message:unknown,transfer:Transferable[]=[])=>new Promise<any>((resolve,reject)=>{worker.onmessage=e=>e.data.error?reject(Error(e.data.error)):resolve(e.data);worker.onerror=()=>reject(Error('Could not start GIF encoder.'));worker.postMessage(message,transfer);});
  try{for(let i=0;i<p.frames.length;i++){progress(`Encoding GIF ${i+1} / ${p.frames.length}`);const c=await engine.composite(p.frames[i]!.revisionId,'flatten',p),rgba=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data;await exchange({rgba:rgba.buffer,width:c.width,height:c.height,delay:p.frames[i]!.durationMs??1000/p.fps,repeat:p.loop==='once'?-1:0},[rgba.buffer]);}
    const {bytes}=await exchange({finish:true});return new Blob([bytes],{type:'image/gif'});
  }finally{worker.terminate();}
}
export async function webm(p:Project,engine:CanvasEngine,progress:(s:string)=>void){const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(t=>MediaRecorder.isTypeSupported(t));if(!mime)throw Error('WebM export is not available in this browser. Use GIF or PNG sequence.');const c=document.createElement('canvas');c.width=p.size.width;c.height=p.size.height;const ctx=c.getContext('2d')!;const stream=c.captureStream(0),track=stream.getVideoTracks()[0] as CanvasCaptureMediaStreamTrack;const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8_000_000});const parts:Blob[]=[];const result=new Promise<Blob>((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data);};recorder.onstop=()=>resolve(new Blob(parts,{type:'video/webm'}));recorder.onerror=()=>reject(Error('Video encoding failed.'));});recorder.start();try{for(let i=0;i<p.frames.length;i++){progress(`Recording WebM ${i+1} / ${p.frames.length}`);ctx.drawImage(await engine.composite(p.frames[i]!.revisionId,'flatten',p),0,0);track.requestFrame();await new Promise(r=>setTimeout(r,p.frames[i]!.durationMs??1000/p.fps));}recorder.stop();return await result;}finally{if(recorder.state!=='inactive')recorder.stop();stream.getTracks().forEach(t=>t.stop());}}
export async function contactSheet(p:Project,engine:CanvasEngine){const c=document.createElement('canvas'),cols=Math.min(4,p.frames.length);c.width=cols*320;c.height=Math.ceil(p.frames.length/cols)*260;const ctx=c.getContext('2d')!;ctx.fillStyle='#f4f2e9';ctx.fillRect(0,0,c.width,c.height);for(let i=0;i<p.frames.length;i++){const img=await engine.composite(p.frames[i]!.revisionId,'flatten',p),x=i%cols*320,y=Math.floor(i/cols)*260,scale=Math.min(296/img.width,212/img.height);ctx.drawImage(img,x+(320-img.width*scale)/2,y+12,img.width*scale,img.height*scale);ctx.fillStyle='#263021';ctx.font='14px monospace';ctx.fillText(`F${String(i+1).padStart(2,'0')}${p.frames[i]!.keyframe?'  ◆ KEYFRAME':''}`,x+12,y+246);}return blobFromCanvas(c);}
